### ISSUE TITLE
External use of Discourse

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_forum#1]
Discourse is used for instance to show avatar and MP indicator in UI app (it means that the user must be also authenticated in Discourse when browsing the UI).

**Comment by gberaudo** [comment]
Alternatively, we might want to generate a discourse API key for the user and use it from the UI
to extract informations from discourse on behalf of the user.

**Comment by asaunier** [comment]
You mean that the `user` directive in the UI could make a request to the Discourse API to get the user's avatar for instance?

**Comment by gberaudo** [comment]
Maybe not for avatars as it is probably public information. But yes for MP.

**Comment by gberaudo** [comment]
For avatars, it would be easier to do it the other way: having Discourse take the avatar from the UI.

**Comment by asaunier** [comment]
> having Discourse take the avatar from the UI.

What avatar from the UI?
There is no plan to add an avatar in the UI.

**Comment by fjacon** [comment]
What is the status of this issue ?
Can we close it ?
