### ISSUE TITLE
Forum migrating : the number of user responses is always 0

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_forum#10]
During the forum migrating, the number of posts of each user has not been migrated.
PunBB counts only the number of posts, whereas Discourse counts the topics (the user has posted the first post of a topic) and the responses.
We can copy the PunBB user post count to discourse user response count.

**Comment by asaunier** [comment]
What about directly updating the post count after migrating the messages?

**Comment by fbunoz** [comment]
The post count include deleted posts.
But if it is easier to update the post count, it is OK.

**Comment by gberaudo** [comment]
In punbb: app_users_private_data.num_posts.
In discourse: user_stats.post_count.

**Comment by gberaudo** [comment]
@fbunoz, I have checked http://c2cpc34.camptocamp.com:3000/users?order=post_count&period=all and it seems realistic: there are both stats for the number of topics created (sujets) and the number of posts (réponses). The max count of `réponses` is 1000, which makes sense for an import of 5% of the posts.
Please reopen if I missed something.

**Comment by asaunier** [comment]
> I have checked http://c2cpc34.camptocamp.com:3000/users?order=post_count&period=all

Is it an admin only page? I keep being redirected to Discourse main page when loading this URL.

**Comment by gberaudo** [comment]
Not for admin, but for connected users.

**Comment by fbunoz** [comment]
I checked, and the counts are OK.
