### ISSUE TITLE
Forum migrating  : the post IP address has not been migrated

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_forum#11]
Discourse does not store the IP address for each post. Only the last IP address used by an user, and the regsiter IP (but unused in V6 ?), are stored.
But the French law requires that the IP address must be stored during one year.
Moreover, it is useful for moderators, despite the common IPs, the redistributed IPs, and the TOR IPs.

IP features will evolve in discourse :

> Sure long term we should store ip addresses of all logged on sessions and allow admins to log off particular sessions selectively or get info about them.

https://meta.discourse.org/t/store-more-than-one-ip-address-per-user/24155/4

Then, it is better to migrate the V5 post IP address in a new column in post table, and to improve discourse to save the V6 post IP, waiting for new features.

**Comment by gberaudo** [comment]
I think it is better to keep the discourse database structure as-is.
The IP address of the punbb posts will be available in the latest punbb dump.
When the feature comes to discourse and the database is upgraded, it will be
easy to read the dump and insert the IPs in old posts.

Thoughts on this @asaunier?

**Comment by asaunier** [comment]
I also think it is better to keep Discourse DB untouched.

**Comment by gberaudo** [comment]
Closing, @fbunoz feel free to reopen if there is any new information.
