### ISSUE TITLE
Forum migrating : names of guest posters

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_forum#14]
With the current state of the migration tool, old messages posted as guest are affected to user "System" (the guest poster pseudo is no longer displayed).

The solution suggested by @gberaudo seems OK for the association: prefix those messages by some mention like `Posted as guest by <pseudo>`.

Nice to have: use a localized prefix depending on the language of the discussion (perhaps it can be detected by figure the main forum original category which are "it", "de", etc. in v5, default would be "fr").

**Comment by gberaudo** [comment]
Handled in branch https://github.com/c2corg/discourse/tree/import_punbb.

**Comment by asaunier** [comment]
Cool thanks a lot!

> mapped[:raw] = "Posted as guest by #{m['poster']}\n#{mapped[:raw]}"

To make it clearer that it's not part of the original message, perhaps you could add a blank line between it and the message. Perhaps also add some italic tags as well?

**Comment by gberaudo** [comment]
There is already a new line. Did you missed the `\n`?

**Comment by gberaudo** [comment]
@asaunier, there is now also italics.

**Comment by asaunier** [comment]
> There is already a new line. Did you missed the \n?

I have noticed it, but `\n` only makes the following content appear on the next line, not after a blank line, doesn't it?

**Comment by gberaudo** [comment]
I understand what you mean now. Will it not waste space, especially on small screens?

**Comment by asaunier** [comment]
I don't think that's a problem. It doesn't "waste" that much space and is much clearer. Anyway people will have to scroll to read the thread.

**Comment by fbunoz** [comment]
The prefix sentence for guest posters can be translated to the forum language, which can be found in the forum field : punbb_forums.culture (which can contain : fr it en de es ca eu)
https://github.com/c2corg/camptocamp.org/blob/master/data/sql/tables/punbb.sql.in#L123
