### ISSUE TITLE
Redirect old forum URLs

### ISSUE THREAD

**Issue by gberaudo** [c2corg/v6_forum#15]
https://meta.discourse.org/t/redirecting-old-forum-urls-to-new-discourse-urls/20930
#3

**Comment by gberaudo** [comment]
@mfournier, @asaunier should the mapping be done in Discourse or using a proxy like nginx?

**Comment by asaunier** [comment]
What do you think?
If it comes out of the box in discourse, it's probably easier to use Discourse.
But what about performances?

In the topic you have pointed someone asks:

> Wouldn't it be insanely faster and less resource-intensive to provide nginx a rewrite map file to handle this, instead of making Discourse process every request?
> https://meta.discourse.org/t/redirecting-old-forum-urls-to-new-discourse-urls/20930/10

but I have not read the topic...

**Comment by gberaudo** [comment]
Yes, my question is about performance: do we plan to have an nginx or alike as fronted?

**Comment by gberaudo** [comment]
I read somewhere that the discourse docker image uses nginx internally. But not sure if it would be
good practice to reuse it or if it is better to handle that outside of the image.

**Comment by gberaudo** [comment]
http://blog.haproxy.com/2015/01/26/web-application-name-to-backend-mapping-in-haproxy/

**Comment by arnaud-morvan** [comment]
Note that we have some punbb ids already stored in discourse database during import.

See the tables `group_custom_fields`, `user_custom_fields`, `category_custom_fields`, `post_custom_fields`.
Table `topic_custom_fields` exists but is not filled during import.

Custom field tables are already indexed on fielname and value, and the value is a text field.

**Comment by arnaud-morvan** [comment]
Permalinks can be created with : 

```
def create_post_permalinks
  puts '', "creating posts redirections"
  PostCustomField.where(name: 'import_id').pluck(:post_id, :value).each do |post_id, import_id|
    Permalink.create(url: "/viewtopic.php?pid=#{import_id}", post_id: post_id)
  end
end
```

**Comment by arnaud-morvan** [comment]
J'ai ajouter des permaliens dans le script de migration.
@mfournier : Il faudra sans doute prévoir qque chose dans le service frontal de production si l'url vers le forum à changé (http://camptocamp.org/forums/ => ?)

**Comment by jmarcmod** [comment]
@arnaud-morvan 
Sur la beta, pas d'amélioration : les liens internes au forum V5 n'ont pas été transformés en liens V6, donc seront inutilisables...
Il s'agit là d'une perte énorme ; notamment pour les modos forum, modos topoguide, et membres de l'association, qui travaillent sur les forums privés essentiellement par liens.

**Comment by arnaud-morvan** [comment]
Je n'ai pas exécuté le rebake sur la démo : https://github.com/c2corg/v6_forum/issues/32#issuecomment-248318602
Le problème des liens internes : ils sont à recalculer à chaque fois que l'on change le nom d'hote, et donc à chaque déplacement de la base (migration => démo) et cela demande ENORMEMENT de ressources.

**Comment by stef74** [comment]
A relancer peut être une fois pour verifier que ca fonctionne bien ?

**Comment by jmarcmod** [comment]
@arnaud-morvan 
Si je comprends bien, ça devrait fonctionner sur la version définitive ? bonne nouvelle !

**Comment by stef74** [comment]
@arnaud-morvan comment on s'assure que ca va bien fonctionner (même sur un echantillon reduit) ?

**Comment by arnaud-morvan** [comment]
Nous sommes en train de mettre en place un serveur spécifique pour les migrations récursives, nous allons ajouter cette tâche en fin de process. Nous verrons ensuite s'il reste des problèmes.

**Comment by fbunoz** [comment]
Je n'ai pas bien pigé cette histoire de permalien (c'est ce qui se trouve ici : https://forum.demov6.camptocamp.org/admin/customize/permalinks ? )
Mais si on arrive à transformer un lien punbb en lien discourse, on peut le remplacer sans le nom de domaine : 
- Si le lien est sur du texte, on ne change rien au bbcode ( [url=/t/test-again/172115]texte[/url] )
- Si le lien est nu, on ajoute les balises url autour d'un texte, en prenant l'ID par exemple : [url=/t/test-again/172115]t172115[/url]

Ca fonctionne : http://forum.demov6.camptocamp.org/t/test-again/172115/2

**Comment by arnaud-morvan** [comment]
Merci de donner les exemples en V5 car je n'y ai pas accès, si possible avec le lien vers le post en question.

**Comment by jmarcmod** [comment]
Comme stef74 voulait que je crée une issue dédiée, voici des exemples de liens cassés V5/V6 : [#52](https://github.com/c2corg/v6_forum/issues/52)

**Comment by fbunoz** [comment]
Des exemples de liens internes au forum V5 : http://www.camptocamp.org/forums/viewtopic.php?pid=1283509#p1283509
C'est le post qui annonce cette fonctionnalité. Depuis, tous les liens internes sont automatiquement transformée selon cette syntaxe à l'enregistrement du post, depuis je ne sais plus quelle date.

**Comment by jmarcmod** [comment]
Issue à fermer car désormais gérée dans la [#52](https://github.com/c2corg/v6_forum/issues/52) .
