### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_forum#16]
Logging out in discourse now works as expected (logged out in UI as well).
I notice that when clicking the "Log out" button in Discourse, the auth page is briefly displayed before being redirected to Discourse main page. Would it be possible to skip the auth page?

**Comment by gberaudo** [comment]
We must redirect to some page of the UI to trigger the loggout.
We do not have to use the auth pas; it would be possible to create ad dedicated page.

**Comment by asaunier** [comment]
@gberaudo told me that one must be redirected to a UI page in order to be logged out in the UI. Then the user is redirected to the forum.

Closing.
