### ISSUE TITLE
Migrate restricted categories permissions

### ISSUE THREAD

**Issue by gberaudo** [c2corg/v6_forum#18]

**Comment by gberaudo** [comment]
@fbunoz, I am investigationg if it is possible to migrate the punbb groups and permissions to discourse.
I found the punbb_groups table, but not where it was associated to forum categories.

Do you know where it is done?

**Comment by fbunoz** [comment]
The forum permission for each group are set in forum_perms table.
There is one line for each (forum_id , group_id). But each group has
default permissions, and the forum permissions for a group, which are
identical to the default permissions of the group, are not stored.

The user group is set in users table.

**Comment by gberaudo** [comment]
Thanks, but how does a user is associated to a group?
Is it the `moderator` column of punbb_forums?

**Comment by fbunoz** [comment]
An user is associated at a group by setting the group id in the group_id
column of the users table (line : id = user id).

**Comment by fbunoz** [comment]
I create a branch to commit some changes on user groups migrating scrpt : 
https://github.com/c2corg/discourse/commit/0e3ba925aeeb6e2c75c6fa9e9351b1062cd2ca2b

**Comment by gberaudo** [comment]
Thanks @fbunoz for the commit. It looks good.

**Comment by fjacon** [comment]
Can we close this issue ?

**Comment by gberaudo** [comment]
The permissions are migrated in a very coarse grain: the public forums stay public, all other forums are made private by the migration script. In addition, users are associated to groups.

In a second step, using the Discourse administration interface, the group permissions for each forum are set.
