### ISSUE TITLE
Post migrating and parser improvment

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_forum#20]
It is not useful to remove unsupported BBcode tag. Today, only the [video] tags are removed.
The post parser will be improved by the assoce to support [video] tags and others V5 tags.

If you want to improve the parser, the V5 post parser is here : 
https://github.com/c2corg/camptocamp.org/blob/master/web/forums/include/parser.php#L997
The sub functions are defined in the same file.

**Comment by fjacon** [comment]
Post messages are now kept unmodified.

**Comment by jmarcmod** [comment]
Issue à fermer.
