### ISSUE TITLE
Storage of uploaded images and avatar

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_forum#21]
If Discourse is installer in a Docker container, where would the images uploaded in the posts and the users avatars be stored? They must be saved in a permanent storage, unlike a Docker container.
Does Discourse support S3 storages for instance?

**Comment by gberaudo** [comment]
For information, there are drawbacks using S3: https://meta.discourse.org/t/amazon-s3-is-not-deprecated-in-1-3-for-image-attachment-storage/26594/108.

**Comment by asaunier** [comment]
Concerning the images uploaded in the forum posts, is it possible to use a third-party image hosting service? For instance in v5, the images are hosted on http://imgur.com/

**Comment by gberaudo** [comment]
All dynamic data is stored in /var/discourse/shared/standalone/ and mounted inside the container.
This includes uploaded images and also postgres, redis, backups, logs...

**Comment by gberaudo** [comment]
Regarding imgur, it seems there is/was some automatic integration inside Discourse. This need to be checked. https://meta.discourse.org/t/til-discourse-can-embed-imgur-albums-and-galleries/27406
