### ISSUE TITLE
Configure Discourse with the demo instance

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_forum#23]
As for now the login/logout and username sync does not work between the UI demo instance and the Discourse demo instance.

@gberaudo I have probably missed some config but I am not sure what I should do. Is there a doc somewhere?

**Comment by asaunier** [comment]
Seen in the apache logs:
- when logging out

> [Tue May 17 09:55:05.525649 2016] [wsgi:error] [pid 32166] Error logging out of discourse for 377
> [Tue May 17 09:55:05.526036 2016] [wsgi:error] [pid 32166] Traceback (most recent call last):
> [Tue May 17 09:55:05.526047 2016] [wsgi:error] [pid 32166]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/c2corg_api/views/user.py", line 615, in post
> [Tue May 17 09:55:05.526053 2016] [wsgi:error] [pid 32166]     result['discourse_user'] = client.logout(userid, settings)
> [Tue May 17 09:55:05.526063 2016] [wsgi:error] [pid 32166] TypeError: logout() takes 2 positional arguments but 3 were given
- when logging in

> [Tue May 17 09:55:51.208376 2016] [wsgi:error] [pid 32166] Could not request nonce
> [Tue May 17 09:55:51.208629 2016] [wsgi:error] [pid 32166] Traceback (most recent call last):
> [Tue May 17 09:55:51.208641 2016] [wsgi:error] [pid 32166]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/requests/packages/urllib3/util/timeout.py", line 130, in _validate_timeout
> [Tue May 17 09:55:51.208648 2016] [wsgi:error] [pid 32166]     if value < 0:
> [Tue May 17 09:55:51.208653 2016] [wsgi:error] [pid 32166] TypeError: unorderable types: str() < int()
> [Tue May 17 09:55:51.208737 2016] [wsgi:error] [pid 32166] 
> [Tue May 17 09:55:51.208744 2016] [wsgi:error] [pid 32166] During handling of the above exception, another exception occurred:
> [Tue May 17 09:55:51.208749 2016] [wsgi:error] [pid 32166] 
> [Tue May 17 09:55:51.208754 2016] [wsgi:error] [pid 32166] Traceback (most recent call last):
> [Tue May 17 09:55:51.208759 2016] [wsgi:error] [pid 32166]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/c2corg_api/security/discourse_client.py", line 91, in request_nonce
> [Tue May 17 09:55:51.208764 2016] [wsgi:error] [pid 32166]     r = requests.get(url, allow_redirects=False, timeout=self.timeout)
> [Tue May 17 09:55:51.208769 2016] [wsgi:error] [pid 32166]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/requests/api.py", line 67, in get
> [Tue May 17 09:55:51.208774 2016] [wsgi:error] [pid 32166]     return request('get', url, params=params, *_kwargs)
> [Tue May 17 09:55:51.208779 2016] [wsgi:error] [pid 32166]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/requests/api.py", line 53, in request
> [Tue May 17 09:55:51.208784 2016] [wsgi:error] [pid 32166]     return session.request(method=method, url=url, *_kwargs)
> [Tue May 17 09:55:51.208789 2016] [wsgi:error] [pid 32166]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/requests/sessions.py", line 468, in request
> [Tue May 17 09:55:51.208794 2016] [wsgi:error] [pid 32166]     resp = self.send(prep, *_send_kwargs)
> [Tue May 17 09:55:51.208799 2016] [wsgi:error] [pid 32166]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/requests/sessions.py", line 576, in send
> [Tue May 17 09:55:51.208804 2016] [wsgi:error] [pid 32166]     r = adapter.send(request, *_kwargs)
> [Tue May 17 09:55:51.208810 2016] [wsgi:error] [pid 32166]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/requests/adapters.py", line 362, in send
> [Tue May 17 09:55:51.208815 2016] [wsgi:error] [pid 32166]     timeout = TimeoutSauce(connect=timeout, read=timeout)
> [Tue May 17 09:55:51.208820 2016] [wsgi:error] [pid 32166]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/requests/packages/urllib3/util/timeout.py", line 97, in __init__
> [Tue May 17 09:55:51.208825 2016] [wsgi:error] [pid 32166]     self._connect = self._validate_timeout(connect, 'connect')
> [Tue May 17 09:55:51.208830 2016] [wsgi:error] [pid 32166]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/requests/packages/urllib3/util/timeout.py", line 136, in _validate_timeout
> [Tue May 17 09:55:51.208835 2016] [wsgi:error] [pid 32166]     "int or float." % (name, value))
> [Tue May 17 09:55:51.208845 2016] [wsgi:error] [pid 32166] ValueError: Timeout value connect was 10, but it must be an int or float.
> [Tue May 17 09:55:51.208888 2016] [wsgi:error] [pid 32166] 
> [Tue May 17 09:55:51.209711 2016] [wsgi:error] [pid 32166] Error logging into discourse for 377
> [Tue May 17 09:55:51.209743 2016] [wsgi:error] [pid 32166] Traceback (most recent call last):
> [Tue May 17 09:55:51.209752 2016] [wsgi:error] [pid 32166]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/requests/packages/urllib3/util/timeout.py", line 130, in _validate_timeout
> [Tue May 17 09:55:51.209758 2016] [wsgi:error] [pid 32166]     if value < 0:
> [Tue May 17 09:55:51.209763 2016] [wsgi:error] [pid 32166] TypeError: unorderable types: str() < int()
> [Tue May 17 09:55:51.209768 2016] [wsgi:error] [pid 32166] 
> [Tue May 17 09:55:51.209772 2016] [wsgi:error] [pid 32166] During handling of the above exception, another exception occurred:
> [Tue May 17 09:55:51.209777 2016] [wsgi:error] [pid 32166] 
> [Tue May 17 09:55:51.209782 2016] [wsgi:error] [pid 32166] Traceback (most recent call last):
> [Tue May 17 09:55:51.209787 2016] [wsgi:error] [pid 32166]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/c2corg_api/security/discourse_client.py", line 91, in request_nonce
> [Tue May 17 09:55:51.209834 2016] [wsgi:error] [pid 32166]     r = requests.get(url, allow_redirects=False, timeout=self.timeout)
> [Tue May 17 09:55:51.209844 2016] [wsgi:error] [pid 32166]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/requests/api.py", line 67, in get
> [Tue May 17 09:55:51.209850 2016] [wsgi:error] [pid 32166]     return request('get', url, params=params, *_kwargs)
> [Tue May 17 09:55:51.209855 2016] [wsgi:error] [pid 32166]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/requests/api.py", line 53, in request
> [Tue May 17 09:55:51.209860 2016] [wsgi:error] [pid 32166]     return session.request(method=method, url=url, *_kwargs)
> [Tue May 17 09:55:51.209865 2016] [wsgi:error] [pid 32166]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/requests/sessions.py", line 468, in request
> [Tue May 17 09:55:51.209870 2016] [wsgi:error] [pid 32166]     resp = self.send(prep, *_send_kwargs)
> [Tue May 17 09:55:51.209875 2016] [wsgi:error] [pid 32166]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/requests/sessions.py", line 576, in send
> [Tue May 17 09:55:51.209880 2016] [wsgi:error] [pid 32166]     r = adapter.send(request, *_kwargs)
> [Tue May 17 09:55:51.209885 2016] [wsgi:error] [pid 32166]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/requests/adapters.py", line 362, in send
> [Tue May 17 09:55:51.209890 2016] [wsgi:error] [pid 32166]     timeout = TimeoutSauce(connect=timeout, read=timeout)
> [Tue May 17 09:55:51.209896 2016] [wsgi:error] [pid 32166]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/requests/packages/urllib3/util/timeout.py", line 97, in __init__
> [Tue May 17 09:55:51.209901 2016] [wsgi:error] [pid 32166]     self._connect = self._validate_timeout(connect, 'connect')
> [Tue May 17 09:55:51.209906 2016] [wsgi:error] [pid 32166]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/requests/packages/urllib3/util/timeout.py", line 136, in _validate_timeout
> [Tue May 17 09:55:51.209911 2016] [wsgi:error] [pid 32166]     "int or float." % (name, value))
> [Tue May 17 09:55:51.209917 2016] [wsgi:error] [pid 32166] ValueError: Timeout value connect was 10, but it must be an int or float.
> [Tue May 17 09:55:51.209921 2016] [wsgi:error] [pid 32166] 
> [Tue May 17 09:55:51.209926 2016] [wsgi:error] [pid 32166] During handling of the above exception, another exception occurred:
> [Tue May 17 09:55:51.209931 2016] [wsgi:error] [pid 32166] 
> [Tue May 17 09:55:51.209935 2016] [wsgi:error] [pid 32166] Traceback (most recent call last):
> [Tue May 17 09:55:51.209940 2016] [wsgi:error] [pid 32166]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/c2corg_api/views/user.py", line 569, in post
> [Tue May 17 09:55:51.209945 2016] [wsgi:error] [pid 32166]     r = client.redirect_without_nonce(user)
> [Tue May 17 09:55:51.209950 2016] [wsgi:error] [pid 32166]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/c2corg_api/security/discourse_client.py", line 143, in redirect_without_nonce
> [Tue May 17 09:55:51.209955 2016] [wsgi:error] [pid 32166]     nonce = self.request_nonce()
> [Tue May 17 09:55:51.209960 2016] [wsgi:error] [pid 32166]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/c2corg_api/security/discourse_client.py", line 95, in request_nonce
> [Tue May 17 09:55:51.209965 2016] [wsgi:error] [pid 32166]     raise Exception('Could not request nonce')
> [Tue May 17 09:55:51.209973 2016] [wsgi:error] [pid 32166] Exception: Could not request nonce

**Comment by gberaudo** [comment]
Opened https://github.com/c2corg/v6_api/pull/289.
