### ISSUE TITLE
Issues with first full import

### ISSUE THREAD

**Issue by gberaudo** [c2corg/v6_forum#24]
A first import of the v5 data was conducted. It took a long time ~10 days and there are many issues.
The data was imported in a dedicated instance of Discourse and then dumped and imported in the Docker instance of Discourse.

Issues:
- [x] Quoted posts images are using hard coded urls `localhost:3000`;
- [x] Categories seem to create a post whose id conflicts with v5 ones (see one-one rule for post ids);
- [ ] Many quotes could not be rewritten (a small fraction could be due to the failing one-one rule, but must are failing for unknown reason) There should be a log of all quote rewritting;
- [x] The comment category is not removed from main page (only its parent category);
- [x] Admins and modos (forum) are not migrated;
- [ ] The synchro from UI to Discourse does not work (and the change is saved in the UI anyway!!!).

Note:
- [x] Ideally, the Docker and standalone instances should be of the same version (stable 1.5.2);

**Comment by jmarcmod** [comment]
Merci, je vais regarder ça de près !

**Comment by fbunoz** [comment]
> Categories seem to create a post whose id conflicts with v5 ones (see one-one rule for post ids);

A solution is : 
- modify the topic and posts counters before creating the categories (set them to a value higher than the last v5 topic and post)
- create the categories
- migrate the posts and topics (which doesn't need the counter value if the migrating set the v5 ID directly).

The admin right seem not to be migrating (I don't have the admin right).

**Comment by asaunier** [comment]
> The admin right seem not to be migrating (I don't have the admin right).

By the way is the migration script supposed to propagate the "moderator" rights? Does this role actually exist in Discourse or is it the same than "admin"?

**Comment by fbunoz** [comment]
I don't know what the script do exactly.
But there are admin and moderators in discourse (as in any forum application).

**Comment by gberaudo** [comment]
The script is supposed to migrate admins and moderators. @fbunoz, I granted you admin rights manually.
Adding this to the `to investigate` list.

**Comment by jmarcmod** [comment]
Mes droits modérateurs V5 n'ont visiblement pas migré.

Par ailleurs j'ai pu me connecter avec mon identifiant V5 (jmc) et mon mot de passe V5, mais alors que sur le précédent forum de test mon pseudo discourse était jmc, là c'est jmc2 (sur les anciens posts comme sur les nouveaux). Pourquoi ?

**Comment by gberaudo** [comment]
@jmarcmod, après normalization, si plusieurs utilisateurs ont le même pseudo, ils sont rendus uniques avec un compteur.

Dans v5 tu as quels droits de modérations? J'ai vérifié ton group_id dans la base v4 et il vaut 4.
38 personnes ont été ajouté au groupe `Modo_Topoguide` de Discourse.

**Comment by jmarcmod** [comment]
> après normalization, si plusieurs utilisateurs ont le même pseudo, ils sont rendus uniques avec un compteur

OK, j'avais oublié que mon login n'était unique que selon les règles V5.
A ce propos pour le moment le pseudo Discourse reste issu du _login_ V5, et non du _pseudo forum_ V5, comme nous le souhaitons au final.
J'ai synthétisé notre proposition de migration ici: https://github.com/c2corg/v6_forum/issues/22#issuecomment-222550729 dans le but justement qu'à la prochaine version, les nouveaux pseudos soient les anciens pseudos forum (à normalisation près).
Je suis juste désolé de ne pas avoir pu le faire avant cette toute récente migration.

> Dans v5 tu as quels droits de modérations? J'ai vérifié ton group_id dans la base v4 et il vaut 4.
> 38 personnes ont été ajouté au groupe Modo_Topoguide de Discourse.

Modérateur forum.

**Comment by gberaudo** [comment]
OK. Oui merci, je vous ferai un retour prochainement.

Seuls les groupes principaux (avec le plus de personnes) sont créés par le script de migration.
Il faut qu'un admin crée manuellement ces petits groupes et leur donner les droits sur les catégories concernées.

**Comment by jmarcmod** [comment]
> Il faut qu'un admin crée manuellement ces petits groupes et leur donner les droits sur les catégories concernées.

D'ac.
@fbunoz : dès que tu seras opérationnel en admin, tu pourras me donner mes droits modos ?
Faut-il comme la dernière fois que d'abord je change d'adresse mail ? actuellement, c'est user9354@localhost où 9354 est mon ID V5 ; mais je n'ai pas accès à un champ d'édition de l'adresse dans la config de mon profil...
Dans le même ordre d'idée, je ne peux pas changer mon "full name"...
J'imagine que tout ça est configuré par l'admin.

**Comment by gberaudo** [comment]
Le changement du full name et adresse se fait via l'interface principale: http://c2corgv6.demo-camptocamp.com/account.

**Comment by jmarcmod** [comment]
OK.
Mais je suis un peu largué:
- sur discourse: username = jmc2 / name = jmc
- sur l'interface principale: name = J.Marc / forum username = JMarcd1

Je précise que je n'ai encore rien personnalisé !

Ce que moi j'en comprends : 
- sur discourse: "username" = pseudo affiché en haut à gauche de chaque post et avec lequel on peut interpeller un membre (via @) / "name" = nom d'utilisateur, où on peut formater à sa guise avec espace, accents etc. et qui apparait à droite de l'username s'il lui est différent (sauf que ça ne marche plus, à droite de jmc2 devrait apparaitre jmc...)
- sur l'interface principale: "name" = pseudo topoguide ? / "forum username" = ??? est-ce le username ou le name de discourse ? et pourquoi chez moi ne correspond-t’il à rien ?

Visiblement, on peut modifier son pseudo topoguide, et le "forum username". Je vais faire des essais.
Mais au final, combien de "pseudos" ? 3 ? si oui, il y en a un non modifiable...
Et le login, qui est-il dans tout ça ?

En tout cas pour le public, il faudra renommer ces pseudos de manière claire...

_Edit:_ j'ai fait des essais, et aucun des 2 champs ne peut correspondre à un nom d'utilisateur forum non contraint aux normes ; de plus, les modifs n'ont rien changé à mes pseudos sur Discourse...
Pire : je ne peux pas changer de pseudo en revenant au précédent : "Already used forum name".

**Comment by gberaudo** [comment]
Je viens d'essayer, il y a effectivement quelque chose qui cloche dans la synchro avec Discourse.
J'ajoute à la liste, merci.

Il y a bien 3 usernames:
- le pseudo principal (ne se change pas);
- le nom complet (se change dans account 'name');
- le pseudo du forum (se change dans account 'Forum username').

**Comment by jmarcmod** [comment]
Merci, je commence à comprendre !
- pseudo principal : le login, donc ; est-ce exactement le login V5, où y a-t-il eu éventuel reformatage ? auquel cas il faudra le donner aux membres pour qu'ils puissent se connecter...
- nom complet : c'est aussi le pseudo topoguide, donc.
- pseudo forum : OK, celui qu'il faudra migrer avec formatage.

**Comment by fbunoz** [comment]
@gberaudo : 

> J'ai vérifié ton group_id dans la base v4 et il vaut 4.

L'ID de jmarcmod dans la V5 est 9354.
Il est modo forum, le numéro du groupe est 2 normalement.

@jmarcmod : tu as les droits modos, mais je ne sais pas qui te les a donné (je n'ai rien fait).

**Comment by jmarcmod** [comment]
Exact, j'ai les droits modo maintenant, et ça marche.

Autre chose : le nom complet apparait désormais à droite du pseudo, du moins pour moi puisqu'il est différent (pseudo jmc2 / nom complet jmc).
_Edit:_ grâce à une config admin de Bubu.

**Comment by gberaudo** [comment]
@fbunoz, j'ai ajouté les droits modos manuellement à @jmarcmod il y a 8 heures.
Effectivement il est bien groupe 2 dans v5, j'ai mis à jour la TODO liste pour corriger ça. C'est certainement le même problème que pour les admins.

>  Edit: grâce à une config admin de Bubu.

@fbunoz, tu as fait quelque chose spécial pour @jmarcmod?

**Comment by gberaudo** [comment]
@jmarcmod 

> pseudo principal : le login, donc ; est-ce exactement le login V5, où y a-t-il eu éventuel reformatage ? auquel cas il faudra le donner aux membres pour qu'ils puissent se connecter...

Oui il est conservé tel quel!

**Comment by jmarcmod** [comment]
@gberaudo 

> Oui il est conservé tel quel!

Nickel !

> tu as fait quelque chose spécial pour @jmarcmod?

Non, c'est pour tout le monde : le nom complet est désormais affiché à droite du pseudo ; mais il n'apparait que s'il diffère du pseudo, donc il apparait par exemple chez moi et pas chez Bubu.

**Comment by fbunoz** [comment]
For some private forums, the restrictions are not set.
The filter to find the private forums is not correct (https://github.com/c2corg/discourse/blob/import_punbb/script/import_scripts/punbb.rb#L133)
The cause is the key words used : they match the parent category name, but they don't match all private sub categories.
We can improve the filter by adding key words.
But a better solution for sub categories : 
For each sub category : 
- find the parent category
- apply the filter on the parent category name
- if it is true, add restriction on the sub category

**Comment by gberaudo** [comment]
Did you find many forum like these? This issue may be similar to `suppress_from_homepage` which was not applied to the subcategory.

**Comment by fbunoz** [comment]
> Did you find many forum like these?
- Discussions au sein de l’Association
- Conseil d’Administration de l’Association
- Assemblée Générale de l’Association
- Archives Modération Forums
- Purgatoire
- Poubelle
- Articles
- Commission publicité
- all sub categories of "C2C V6" category

I added the restrictions on the demo (not for "C2C v6").

> This issue may be similar to suppress_from_homepage which was not applied to the subcategory.

In the script, suppress_from_homepage is set to true only for category #1 (Comments).
It is correct.
We could add some categories. But it is not critical, we can change this manualy after migrating.

**Comment by gberaudo** [comment]
OK, thanks @fbunoz.

> > This issue may be similar to suppress_from_homepage which was not applied to the subcategory.

I was refering to `The comment category is not removed from main page (only its parent category);` of the TODO list. I manually fixed it after import.

**Comment by fbunoz** [comment]
> I was refering to The comment category is not removed from main page (only its parent category); of the TODO list. I manually fixed it after import.

OK. The bug is that the suppress_from_homepage is set correctly only in the function which create the parent categories, and not in the function creating the sub categories.
But for the comments categories, it is not necessary to create a parent and sub categories. A simple category (at first level) is enough.
In punBB, we have created a parent category and a sub category, because in punBB a topic can be created only in sub category (= "forum"), and a forum must be in a parent category.
In discourse, a topic can be created in a parent or a sub category. Then, we can remove the parent category for "comments", and move the "comments" category to the first level.

**Comment by fbunoz** [comment]
> fbunoz, tu as fait quelque chose spécial pour jmarcmod?

@gberaudo : non, j'ai vu qu'il était modo quand j'ai reçu les droits admin, mais je n'ai rien fait. En tout cas, aucun autre modo V5 n'a les droits modos sur la V6, il y a bien un problème de migration.
La config admin dont parle jmarcmod, c'est l'affichage du nom complet à côté du pseudo dans les posts.

**Comment by fbunoz** [comment]
Sur le forum de la démo Béta, les droits admin et modérateur ne semblent pas avoir été migrés. Le pseudo et le nom complet non plus.
Par ailleurs, quand on s'identifie sur la home de la V6, puis qu'on passe sur le forum, on n'est plus identifié. Et la langue de l'interface du forum n'est pas cohérente avec celle du topoguide.

**Comment by asaunier** [comment]
> Par ailleurs, quand on s'identifie sur la home de la V6, puis qu'on passe sur le forum, on n'est plus identifié.

I have not observed this behaviour: I am authenticated in discourse when authenticating in the UI (guidebook), as expected. Tested with FF and Chrome.

On the other hand, I have noticed that after logging out in the UI, I am still authenticated in discourse. No problem when logging out in discourse: also logged out in the UI.

**Comment by jmarcmod** [comment]
Je n'ai pas de problème non plus avec l'identification, elle est conservée quand je passe de la Home au Forum.

**Comment by fbunoz** [comment]
En effet ça fonctionne quand je me déloggue/reloggue.
C'était juste un problème de cookies pas à jour.
