### ISSUE TITLE
Account page

### ISSUE THREAD

**Issue by jmarcmod** [c2corg/v6_forum#25]
**Problèmes avec la page de gestion d'un compte:**
http://c2corgv6.demo-camptocamp.com/account

1) Impossible de modifier l'**adresse email**:

> error with discourse

2) On peut changer le **nom**, mais il n'est pas pris en compte sur Discourse.

3) On peut changer le **pseudo**, mais:
    a) il n'est pas pris en compte sur Discourse ;
    b) il y a plus de restrictions de formatage que ce qu'impose Discourse: le point '.' et l'underscore '_', entre autres, sont interdits (= il y a un "sens interdit" quand on passe la souris sur "Enregistrer").

Rappel : pour le formatage du pseudo forum V5 en pseudo V6, c'est ici : https://github.com/c2corg/v6_forum/issues/22#issuecomment-222550729

NB : sur ma page de gestion du profil Discourse:
http://c2corgv6-discourse.demo-camptocamp.com/users/jmc2/preferences
j'ai: Nom = jmc / Pseudo = jmc2 / Courriel = user9354@localhost 
tandis que sur la page de gestion du compte Camptocamp j'avais (avant modif perso):
Nom = J.Marc / Pseudo =  JMarcd2 / Courriel = user9354@localhost 
Il semble que lors du dernier import, Discourse n'ait pas récupéré les champs V5 pseudo topoguide (= J.Marc) et pseudo forum (=J.Marc), et ait gardé uniquement le login V5 (jmc pour moi).

**Comment by gberaudo** [comment]
Le problème 2) et 3a) est corrigé par https://github.com/c2corg/v6_api/pull/309

**Comment by fjacon** [comment]
Sur le 3b : il faut que l'association fasse d'abord une normalisatoin des pseudos dans V5 dans le format proposé ici : https://github.com/c2corg/v6_forum/issues/22#issuecomment-222550729

**Comment by gberaudo** [comment]
Le problème 1) est corrigé par https://github.com/c2corg/v6_ui/pull/474

**Comment by jmarcmod** [comment]
Est-ce que ces corrections sont effectives sur l'actuel site de démo (alpha 1), ou alors il faut attendre alpha 2 ?
Car pour le moment, on peut changer l'adresse mail (il y a donc un progrès), mais d'une part elle n'est toujours pas transférée à Discourse, d'autre part après déconnexion et reconnexion, on retombe sur l'ancienne adresse.

**Comment by stef74** [comment]
Merci de refaire un ticket si il reste un point spécifique
