### ISSUE TITLE
[tests alpha 1] Migration V5 -> V6

### ISSUE THREAD

**Issue by jmarcmod** [c2corg/v6_forum#26]
**Voici le résultat de nos premiers tests quant à la dernière version du forum (suite à la migration complète du 30 mai).**
Je suis incapable de savoir ce qui incombe à la SA, et ce qui incombe aux développeurs de  l'association ; mais Bubu saura faire le tri.
### 1) Migration V5 -> V6

**a) Comptes :** cf issue #25 [Page account](https://github.com/c2corg/v6_forum/issues/25)

**b) Invités :** les posts d'invités de la V5 se retrouvent tous sous le même compte 'system', mais désormais le pseudo V5 de ces invités apparait en début de message sous la forme "Posted as guest by pseudo:" ; c'est la bonne solution, mais il faudrait traduire en français.

**c) ID :** les discussions sont repérées par un n° d'ordre qui n'est pas l'ID de la V5 ; et les messages de chaque discussion sont repérés par le n° de la discussion mère et un n° d'ordre dans cette discussion.
On perd ainsi tous les liens V5 pointant sur une discussion ou un message, que ce soit depuis le forum, le topoguide ou depuis un site extérieur.
Ce grave problème, repéré dès la première version du forum de test, n'a pas été réglé.

**d) Citations :** les citations, totales ou partielles, des messages V5 sont bien conservées. Et désormais on peut remonter au message source, très gros progrès ! Quant au pseudo cité, c'est celui de la V5 (ce qui est une bonne chose, ça marque le contexte).

Reste 2 soucis lorsque la citation pointe vers une autre discussion :
- on récupère le message source via le bouton '->',  mais les 2 liens vers ce message, avec nom de la discussion mère, sont bugués ; exemple : http://c2corgv6-discourse.demo-camptocamp.com/t/circonstances-de-lavalanche-au-chaberton-de-mars-2014/142312 (lien http://localhost:3000/t/deces-dun-skieur-du-queyras-dans-une-avalanche-au-chaberton/142102/3 ouvrant une page d'échec de connexion) ;
- l'auteur du message source n'apparait pas toujours, même avec le bouton 'v', pour le connaitre il faut en général revenir au message source.

Sinon un bug pour les citations précédées d'une ligne vierge, les balises [ quote ] et [ /quote ] sont alors visibles et non interprétées ; exemple : http://c2corgv6-discourse.demo-camptocamp.com/t/beau-grimpeur-a-espace-vertical/70977/28

**e) Perte des IP des messages :** il semble ne pas y avoir de solution, on s'en passera.

**f) Mise en forme :** comme Discourse accepte une bonne partie du BBCode, la mise en forme des messages est assez bien conservée (y compris les smileys).

Il y a néanmoins une grosse perte : les images et vidéos insérées ne sont plus intégrées, elle deviennent juste des liens cliquables.
Visiblement, la syntaxe [ img=url ][ /img ] ne passe plus (i.e. celle utilisée depuis quelques temps via le bouton Img), alors que celle-ci : [ img ]url[ /img ] fonctionne encore ; et bien sûr le code d'insertion d'une image du topoguide dans le forum ne fonctionne plus.

Perte aussi du code (balise [ c ]), des spoilers (balise [ spoiler ]) et des couleurs (balise [ color ]), mais moins embêtant.

Autre gros problème : un '+' en début de phrase est automatiquement remplacé par une puce, et donc tous les plussoiements "+ 1" sont cassés !

**g) Abonnements :** ils ont désormais théoriquement migré, mais à vérifier pour ceux qui sont concernés (ce n'est pas mon cas).

NB : j'ai l'impression qu'on est par défaut également abonné à tous les sujets qu'on a créés (abonné sur Discourse = mode "Surveiller") ; c'est un peu lourd, à supprimer si possible.

**h) Compteur de posts par membre :** désormais OK (visible seulement par les modos)

**i) Forums privés :** ils n'apparaissent pas dans les catégories ; mais les discussions de ces forums sont bien présentes ! A corriger, car pour l'instant c'est ingérable (on ne sait pas où aller, ni même où on est...)

**j) Exhaustivité de la migration :** j'ai l'impression qu'il manque plein de discussions ! peut-être la moitié...
Par exemple, dans le forum "discussions escalade", pour le mois de septembre 2014, 60 discussions pour la V5, seulement 25 pour la V6...

**Comment by fjacon** [comment]
Je vais créer une issues par point relevés.

**Comment by jmarcmod** [comment]
a) cf #39 et #25 
b) cf #30 
c) cf #31  et #15 
d) cf #32 
f) cf #33 
g) cf #34 
i) cf #35 
j) cf #36 

e) abandon
h) OK

**Comment by HSERGERAERT** [comment]
@stef74 Pourquoi mettre ce ticket en "blocking" alors qu'il a été décomposé en différents tickets. Pour moi ce ticket devrait être fermé, non ?

**Comment by jmarcmod** [comment]
Même avis qu'Hervé, tout a été dispatché dans les tickets 15, 25, 30 à 36, 39.

**Comment by stef74** [comment]
Les ticket qu'il regroupe sont des sujets migrations ... donc blocking par défintion. Donc soit on considere qu'on le clos ... soit c'est lié à ensemble de ticket qui sont eux souven bloquant.

**Comment by HSERGERAERT** [comment]
Clos, car dispatché, à réouvrir si besoin
