### ISSUE TITLE
Navigation et Edition V6

### ISSUE THREAD

**Issue by jmarcmod** [c2corg/v6_forum#27]
**Voici le résultat de nos premiers tests quant à la dernière version du forum (suite à la migration complète du 30 mai).**
Je suis incapable de savoir ce qui incombe à la SA, et ce qui incombe aux développeurs de l'association ; mais Bubu saura faire le tri.
### 2) Navigation et Edition V6

**a) ID non utilisée :** l'ID des discussions et des messages est invisible, et pas utilisée pour le repérage.
Du coup après déplacement d'un message, les liens vers ce message sont obsolètes ; ils renvoient malgré tout au message via un lien de redirection apparaissant là où était l'ancien message, mais c'est difficile de s'y retrouver, et ces redirections vont vite polluer les discussions.
C'est également le cas pour les citations vers des messages déplacés : passage par un lien de redirection.

**b) Messages déplacés :** ils sont rangés par ordre de déplacement, et non par ordre chronologique (et le premier message déplacé se retrouve soit en tête d'une nouvelle discussion, soit en queue d'une discussion existante). D'où perte de sens de la discussion réceptacle !

**c) URL floues :** un lien vers un message donné montre plusieurs messages consécutifs, difficile de savoir lequel était pointé.
Et pour connaitre l'url d'un message défilant, visible dans le champ url du navigateur, c'est approximativement celle du message en haut de page, mais à condition d'avoir stoppé le défilement quelques secondes.
Pour avoir l'url précise d'un message, il faut cliquer sur la date ou sur le bouton "partager", afin d'ouvrir un cadre (d'où on peut voir le n° de message et copier l'url complète) : peu ergonomique.

Du coup lorsqu'on met un lien interne vers un message, pas sûr que le lecteur comprenne quel est le message visé. Un minimum serait qu'un lien interne positionne le message visé exactement en haut de page (comme c'est le cas actuellement sur la V5), ou alors que le message pointé soit colorisé.

**d) Recherche inefficace :** on peut juste chercher par mot(s) clef(s) sur l'ensemble du forum.
Il y a bien un bouton "Options", mais il est inerte.
Par ailleurs il semble que la recherche ne renvoie pas plus de 50 réponses (mais c'est peut-être configurable en mode admin ?)

Il faudrait trouver des plugins permettant de retrouver au moins les options de recherche de la V5 : filtre par forum, recherche sur titre et/ou corps du message, réponse par discussion ou message.

Autre point déroutant par rapport à la V5 : c'est une recherche approchée (comme Google) et non exacte, ce qui a ses avantages lorsqu'on n'est pas certain de ce qu'on cherche, mais devient pénible quand on obtient trop de réponses parasites.

**e) Pas d'IP de messages :** juste l'IP de la dernière connexion du membre, inopérante pour un suivi par les modos.
D'un autre côté, le suivi par IP aujourd'hui devient difficile (trop d'IP changeantes, ou partagées (sur smartphone)), donc pas si grave.

**f) Retour arrière dynamique :** un retour arrière recharge la page, ce qui ralentit et ne ramène pas forcément à l'endroit de la page où on était.
Cela rend la navigation vraiment difficile.
Et le risque est élevé qu'une fausse manip lors de la saisie d'un message fasse perdre le message sans espoir de récupération (alors qu'avec un retour statique, i.e. sans rechargement, on retrouve la fenêtre d'édition avec le texte déjà tapé).

**g) Images fraichement insérées :** un script automatique (de redimensionnement des images ?) semble modifier a posteriori les balises et du coup fait disparaitre l'affichage des images (pourtant visibles lors de la mise en ligne).

**h) Smileys intempestifs :** la ponctuation ':' précédée d'un espace (comme il se doit !) génère un smiley... on ne peut donc pas mettre d'espace avant ':', ou alors il faut bricoler (aller à la ligne, écrire, remonter et ajouter la ponctuation).

**i) Plussoiement :** il est devenu impossible, car un '+' en début de ligne se transforme en puce, on ne peut donc pas écrire '+ 1'.

**j) Liens internes :** ils sont corrects, mais automatiquement transformés en une sorte de citation, ça alourdit inutilement la lecture ; exemple : http://c2corgv6-discourse.demo-camptocamp.com/t/test-liens/169436/7

**k) Citations :**
2 soucis lorsque la citation pointe vers une autre discussion (comme pour la migration, à une nuance près cf le lien d'échec) :
- on récupère le message source via le bouton '->',  mais les 2 liens vers ce message, avec nom de la discussion mère, sont bugués ; exemple : http://c2corgv6-discourse.demo-camptocamp.com/t/test-citations/169440/2 (lien http://c2corgv6-demo.gis.internal/t/test-liens/169436/4 ouvrant une page d'échec de connexion) ;
- l'auteur du message source n'apparait pas toujours, même avec le bouton 'v', pour le connaitre il faut en général revenir au message source.

**l) Avatars :** la saisie d'un avatar ne fonctionne plus : l'image se télécharge, mais "sauvegarder les modifications" ne sauvegarde rien.

**m) Modération des pseudos :** les modérateurs peuvent théoriquement modifier un pseudo, mais ça ne fonctionne pas : message "il y a une erreur lors du chargement de votre pseudo".

**Comment by fjacon** [comment]
Je vais créer des issues correspondants aux problèmes soulevés.

**Comment by fjacon** [comment]
Points a), b) c) d) e) f) h) i) j) : Problèmes Discourse qui ne seront pas corrigés par la SA

point g) : https://github.com/c2corg/v6_forum/issues/37 
point k) : https://github.com/c2corg/v6_forum/issues/38
point l) : je le mets dans https://github.com/c2corg/v6_forum/issues/37 
point m) : le pseudo n'est pas géré dans discourse dans notre cas. Ce n'est pas possible en l'état. Développements probablement non triviaux hors scope pour nous.

**Comment by stef74** [comment]
@fjacon il y a des choses à faire dans ce ticket ?

**Comment by jmarcmod** [comment]
> Points a), b) c) d) e) f) h) i) j) : Problèmes Discourse qui ne seront pas corrigés par la SA
- d) a été partiellement résolu (le bouton "options" de la recherche fonctionne, ce qui permet d'ajouter des filtres).
- i) est traité dans l'issue [#33](url=https://github.com/c2corg/v6_forum/issues/33) 
- j) est résolu.
- e) est abandonné.

> point m) : le pseudo n'est pas géré dans discourse dans notre cas. Ce n'est pas possible en l'état. Développements probablement non triviaux hors scope pour nous.

Pas grave : abandon.

**Comment by jmarcmod** [comment]
@stef74 

>  il y a des choses à faire dans ce ticket ?

Pour la SA, non ; mais il reste du boulot pour les dévs de l'assoce...
A savoir les points a), b), c), d), f), h).

**Comment by jmarcmod** [comment]
Tous ces points sont inhérents à Discourse.
Même l'association ne peut rien y faire.
Il y a juste à espérer que les MAJ de Discourse corrigerons petit-à-petit ces défauts.

Je ferme cette issue.
