### ISSUE TITLE
[tests alpha 1] Ergonomie V6

### ISSUE THREAD

**Issue by jmarcmod** [c2corg/v6_forum#28]
**Voici le résultat de nos premiers tests quant à la dernière version du forum (suite à la migration complète du 30 mai).**
Je suis incapable de savoir ce qui incombe à la SA, et ce qui incombe aux développeurs de l'association ; mais Bubu saura faire le tri.
### 3) Ergonomie V6

**a) Séparation des messages :** les séparateurs entre les différents messages d'une discussion sont à peine visibles : utiliser des cadres, ou des couleurs de fond ?

**b) Accès au menu :** sur desktop, on aimerait une barre ou une colonne gauche (éventuellement repliables), et pas seulement le petit damier en haut à droite ; et ce sur toutes les pages, pas seulement l'accueil.

**c) Largeur d'écran :** le texte n'utilise qu'une partie trop étroite de l'écran (1/3 sur 1920/1080).

_**d) [résolu] Boutons pour créer un message :** cliquer sur "répondre" pour ouvrir la fenêtre d'édition : OK ; mais cliquer ensuite sur "répondre" pour valider, ce n'est pas logique... cependant on n'y peut rien, car il n'y a qu'un champ pour définir ces 2 intitulés._

_**e) [résolu] Boutons pour créer une discussion :** cliquer sur "créer votre sujet" pour ouvrir la fenêtre d'édition : OK ; mais cliquer ensuite sur "créer un sujet" pour valider, ce n'est pas logique non plus ; et là il y a 2 champs séparés ; on pourrait renommer le premier bouton "créer un sujet" et le second "envoyez votre sujet"._

**f) Affichage de la datation d'un message :** actuellement c'est du style 8h, 13j, janv. '13 : inutilisable ! d'autant que tous les messages "proches" ont ainsi la même datation...
Or date + heure (à la minute près) existent (on les obtient en passant la souris sur la datation, ou en cliquant dessus) : il faudrait remplacer l'actuelle datation par cette date + heure (à la minute près) ; avec si possible en lieu et place de la date du jour (resp. de la veille), "aujourd'hui" (resp. "hier") ; bref... comme sur la V5 !

_**g) [résolu] Catégories et forums :** on aimerait une page où tout cela apparait structuré comme dans l'index des forums de la V5... seul moyen d'avoir une vue globale de l'architecture du site, de se familiariser avec les forums existants... et de les retrouver facilement !
Actuellement, trouver le bon forum sur la V6 sans connaitre son nom est une gageure..._

**h) Utilisation avec un smartphone :** très délicate, car boutons trop petits, fenêtres de saisie trop minces (à la création : 2 lignes 1/2 ; à l'édition : 1 ligne 1/2) , ouvertures intempestives pendant qu'on écrit etc. 
A vérifier par Bubu, car perso je n'ai pas de smartphone...

**Comment by stef74** [comment]
Jean marc si tu reduit la taille de ta fentre ... tu aura le rendu smartphone.

**Comment by jmarcmod** [comment]
> Jean marc si tu reduit la taille de ta fentre ... tu aura le rendu smartphone.

Effectivement. Et c'est encore mieux avec l'astuce de Bubu : ctrl + maj + m (testé hier soir).
Mais rien ne vaut l'avis de ceux qui maîtrisent parfaitement l'usage d'un vrai smartphone, c'est pourquoi nos amis adhérents de l'assoce vont être mis à contribution.

**Comment by jmarcmod** [comment]
a) et f) résolus par fbunoz.

Peut-on avoir confirmation que les points b), c) et h) ne seront pas traités par la SA, et donc incombent aux dévs de l'assoce ?

_Edit :_ c) résolu par fbunoz.

**Comment by stef74** [comment]
La SA ne fera rien dans la personnalisation/adaptation de discourse.
