### ISSUE TITLE
Migration of v5 forum (PunBB) to Discourse

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_forum#3]
See for instance:
https://shellycloud.com/blog/2013/12/migrating-polish-ruby-on-rails-forum-from-punbb-to-discourse

![screencapture-shellycloud-com-blog-2013-12-migrating-polish-ruby-on-rails-forum-from-punbb-to-discourse-1452181492380](https://cloud.githubusercontent.com/assets/1192331/12174629/107934e2-b55e-11e5-9640-2497b02dab1b.png)

**Comment by stef74** [comment]
https://meta.discourse.org/t/redirecting-old-forum-urls-to-new-discourse-urls/20930

**Comment by asaunier** [comment]
Thanks @stef74 for the tip!

By the way I have taken a quick look at import scripts provided by Discourse. PunBB is actually supported:
https://github.com/discourse/discourse/blob/master/script/import_scripts/punbb.rb
but the script heavily relies on mysql.

On the other hand the script quoted in the article above ("forum2discourse") seems to suppport postgresql as the import source:
https://github.com/initforthe/forum2discourse/blob/master/bin/forum2discourse#L13-L16

**Comment by stef74** [comment]
@asaunier i'm not sure but migrate only structure and data of current forum to mysql is not a mess. You can easly export the structure ... and for data a simple flat file export of each table can be enough. Some tool can exist probably.

**Comment by stef74** [comment]
http://punbb.informer.com/forums/post/116375/#p116375

**Comment by asaunier** [comment]
Examples for discussions in PunBB with quite advanced formatting:
http://www.camptocamp.org/forums/viewtopic.php?id=114794 (bbcode relativement classique)
http://www.camptocamp.org/forums/viewtopic.php?id=116261
http://www.camptocamp.org/forums/viewtopic.php?id=251192 (images internes, liens internes et externes)
http://www.camptocamp.org/forums/viewtopic.php?id=258183 (vidéo externe)
http://www.camptocamp.org/forums/viewtopic.php?id=271466 (image externe)

**Comment by gberaudo** [comment]
We chose to rework the official punbb migration script. This is done in
https://github.com/c2corg/discourse/blob/import_punbb/script/import_scripts/punbb.rb
