### ISSUE TITLE
Posts d'invités

### ISSUE THREAD

**Issue by fjacon** [c2corg/v6_forum#30]
les posts d'invités de la V5 se retrouvent tous sous le même compte 'system', mais désormais le pseudo V5 de ces invités apparait en début de message sous la forme "Posted as guest by pseudo:" ; c'est la bonne solution, mais il faudrait traduire en français.

**Comment by arnaud-morvan** [comment]
Je suppose que ceci serait à faire en fonction du champ punbb_forums.culture

**Comment by stef74** [comment]
On peut aussi "simplifier" les forum sont surtout utilisé en France ou
faire une chaine qui depende de la langue utilisateur ... mais pas de la
langue du forum (si c'est plus simple).

2016-09-05 16:33 GMT+02:00 Arnaud Morvan notifications@github.com:

**Comment by arnaud-morvan** [comment]
Le problème avec ces posts, c'est que nous n'avons pas d'utilisateur.
J'ai fait la traduction en francais si le forum est en francais, sinon je garde l'anglais.

**Comment by stef74** [comment]
Fait seulement une version francaise ... ca couvrira 95% des cas et tampis
pour le reste.

Le 20 octobre 2016 à 13:06, Arnaud Morvan notifications@github.com a
écrit :

**Comment by jmarcmod** [comment]
Ça me semble très bien ainsi.
Issue à fermer ?
