### ISSUE TITLE
Liens entre les discussions

### ISSUE THREAD

**Issue by fjacon** [c2corg/v6_forum#31]
ID : les discussions sont repérées par un n° d'ordre qui n'est pas l'ID de la V5 ; et les messages de chaque discussion sont repérés par le n° de la discussion mère et un n° d'ordre dans cette discussion.
On perd ainsi tous les liens V5 pointant sur une discussion ou un message, que ce soit depuis le forum, le topoguide ou depuis un site extérieur.
Ce grave problème, repéré dès la première version du forum de test, n'a pas été réglé.

**Comment by gberaudo** [comment]
Cette tâche est suivie dans https://github.com/c2corg/v6_forum/issues/15.
