### ISSUE TITLE
Citations

### ISSUE THREAD

**Issue by fjacon** [c2corg/v6_forum#32]
les citations, totales ou partielles, des messages V5 sont bien conservées. Et désormais on peut remonter au message source, très gros progrès ! Quant au pseudo cité, c'est celui de la V5 (ce qui est une bonne chose, ça marque le contexte).

Reste 2 soucis lorsque la citation pointe vers une autre discussion :

```
on récupère le message source via le bouton '->', mais les 2 liens vers ce message, avec nom de la discussion mère, sont bugués ; exemple : http://c2corgv6-discourse.demo-camptocamp.com/t/circonstances-de-lavalanche-au-chaberton-de-mars-2014/142312 (lien http://localhost:3000/t/deces-dun-skieur-du-queyras-dans-une-avalanche-au-chaberton/142102/3 ouvrant une page d'échec de connexion) ;
l'auteur du message source n'apparait pas toujours, même avec le bouton 'v', pour le connaitre il faut en général revenir au message source.
```

Sinon un bug pour les citations précédées d'une ligne vierge, les balises [ quote ] et [ /quote ] sont alors visibles et non interprétées ; exemple : http://c2corgv6-discourse.demo-camptocamp.com/t/beau-grimpeur-a-espace-vertical/70977/28

**Comment by arnaud-morvan** [comment]
Discourse posts.cooked has to be refreshed with the domain name : 

```
./launcher enter app
discourse remap localhost:3000 c2corgv6-discourse.demo-camptocamp.com
rake posts:rebake
```

source :
https://meta.discourse.org/t/change-the-domain-name-or-rename-my-discourse/16098

**Comment by arnaud-morvan** [comment]
Le problème de ce post n'est pas lié à la ligne vierge.

discourse n'interprête pas les citations sans nom d'utilisateur, je peux éventuellement mettre un nom générique du type "invité".

discourse n'interprête pas les citation imbriquée, ce post à des citations imbriquées sur 3 niveaux. La par contre, je ne vois vraiment pas ce que je peux faire.

**Comment by asaunier** [comment]
> discourse n'interprête pas les citation imbriquée, ce post à des citations imbriquées sur 3 niveaux.

C'est vraiment nécessaire de supporter des trucs comme ça ?

**Comment by stef74** [comment]
Merci de ne passer plus de temps sur ces problematique de migration (si
j'ai compris le fond du problème). Il y a d'autre sujet bien plus utile ;-)

2016-10-20 13:43 GMT+02:00 Alex Saunier notifications@github.com:

**Comment by jmarcmod** [comment]
@arnaud-morvan 

> Reste 2 soucis **lorsque la citation pointe vers une autre discussion**

Le 1er est corrigé (lien vers le message source), mais pas le second : **il manque le pseudo de l'auteur du message source ; n'apparait qu'un micro avatar, inutilisable.**
Exemple : https://forum.demov6.camptocamp.org/t/pictogramme-pour-sorties-ornitho/172021

> Sinon un bug pour les citations précédées d'une ligne vierge, les balises [ quote ] et [ /quote ] sont alors visibles et non interprétées

Ce bug semble mystérieusement corrigé !

> discourse n'interprête pas les citation imbriquée, ce post à des citations imbriquées sur 3 niveaux. La par contre, je ne vois vraiment pas ce que je peux faire.

L'important, c'est que désormais les citations imbriquées de la V5 sont bien interprétées sur la V6 ; je n'ai pas observé de bug d'affichage.
En revanche c'est vrai que sur la V6 on ne pourra plus faire de nouvelles citations imbriquées (si ce n'est en bricolant la balise [ quote ] à la main) ; mais comme dit par Alex, ce n'est vraiment pas indispensable ! Au contraire, ça poussera les gens à cibler leur citation, plutôt que de citer un message en son entier.
Bref, la bonne nouvelle, c'est qu'il n'y a rien à faire ! (à part l'absence de pseudo de la source lors d'une citation en provenance d'une autre discussion, cf début de ce post).

**Comment by arnaud-morvan** [comment]
Concernant l'affichage des citations dans discourse, je laisse le soin à l'association de faire des recherche sur ce qu'il est possible de faire.

> Sinon un bug pour les citations précédées d'une ligne vierge, les balises [ quote ] et [ /quote ] sont alors visibles et non interprétées

Ce bug n'était pas lié à une ligne vierge, mais qu'il manquait le nom d'utilisateur.

J'ai mis [quote="Citation"] pour les citation sans utilisateur.
