### ISSUE TITLE
Mise en forme

### ISSUE THREAD

**Issue by fjacon** [c2corg/v6_forum#33]
Mise en forme : comme Discourse accepte une bonne partie du BBCode, la mise en forme des messages est assez bien conservée (y compris les smileys).

Il y a néanmoins une grosse perte : les images et vidéos insérées ne sont plus intégrées, elle deviennent juste des liens cliquables.
Visiblement, la syntaxe [ img=url ][ /img ] ne passe plus (i.e. celle utilisée depuis quelques temps via le bouton Img), alors que celle-ci : [ img ]url[ /img ] fonctionne encore ; et bien sûr le code d'insertion d'une image du topoguide dans le forum ne fonctionne plus.

Perte aussi du code (balise [ c ]), des spoilers (balise [ spoiler ]) et des couleurs (balise [ color ]), mais moins embêtant.

Autre gros problème : un '+' en début de phrase est automatiquement remplacé par une puce, et donc tous les plussoiements "+ 1" sont cassés !

**Comment by gberaudo** [comment]
Lié à https://github.com/c2corg/v6_forum/issues/20.

**Comment by fjacon** [comment]
A-t-on un exemple de tags image standard qui ne fonctionne pas ?

Sinon, pour le reste, ce sera à l'association de réimplémenter les spécificités de V5.

**Comment by stef74** [comment]
Peux-tu evaluer de votre coté la prise en compte de ces specificités (à
mutualiser avec l'edition de document v6_ui). On prendra ensuite la
décision avec tous les élèments.

2016-06-23 14:11 GMT+02:00 Frédéric Jacon notifications@github.com:

**Comment by asaunier** [comment]
>  à mutualiser avec l'edition de document v6_ui

Ce n'est probablement pas mutualisable car ce sont deux applis différentes avec des technos différentes : python pour les documents, ruby (ou javascript ?) pour discourse.

**Comment by stef74** [comment]
Ok mais les concept et algo sont probalement les mêmes

2016-06-23 15:02 GMT+02:00 Alex Saunier notifications@github.com:

**Comment by jmarcmod** [comment]
> A-t-on un exemple de tags image standard qui ne fonctionne pas ?

http://c2corgv6-discourse.demo-camptocamp.com/t/le-jeu-du-sommet/111013/12931
Lien cliquable OK, mais image pas affichée.
C'est le cas de toutes les images insérées via le bouton [ img ] de la V5 ces 2 ou 3 dernières années (et donc de la plupart des images V5 récentes), syntaxe [ img=url ][ /img ]

L'ancienne syntaxe elle fonctionne:
http://c2corgv6-discourse.demo-camptocamp.com/t/le-jeu-du-sommet/111013/158
syntaxe [ img ]url[ /img ]

**Comment by arnaud-morvan** [comment]
Pour ma part, je pense que nous devrions remplacer toutes les balises images par la syntaxe HTML produite par l'éditeur de Discourse, le résultat sera plus homogène et il sera ainsi plus facile de changer les chemins si nous changeons d'url pour le stockage des images du guidebook.

**Comment by arnaud-morvan** [comment]
Concernant les +1, il ne sont pas cassés, seulement les + 1 (notez l'espace devant le 1), et ca me parait assez normal en soit.
Je vais tout de même ajouter ceci : `s.gsub!(/^\+ 1$/, '+1')`

**Comment by arnaud-morvan** [comment]
Pour la balise color, il faut installer un plugin : https://github.com/discourse/discourse-bbcode-color

**Comment by jmarcmod** [comment]
> seulement les + 1 (notez l'espace devant le 1), et ça me parait assez normal en soit

Oui et non : il n'y a pas d'espace autour de '+' lorsqu'on saisit une formule mathématique dans un logiciel de calcul ; en revanche il y en a à l'affichage dans un texte mathématique... d'ailleurs les traitements de texte scientifiques ajoutent automatiquement ces espaces.
D'où l'habitude de certains d'écrire '+ 1' :)

> Je vais tout de même ajouter ceci

Nickel !

**Comment by jmarcmod** [comment]
@arnaud-morvan 

> les images et vidéos insérées ne sont plus intégrées, elle deviennent juste des liens cliquables.

Sur la beta, ça semble OK pour les images, du moins avec la syntaxe classique [ img ]url[ /img ] ; reste le problème des vidéos (mais pas majeur).

> Visiblement, la syntaxe [ img=url ][ /img ] ne passe plus (i.e. celle utilisée depuis quelques temps via le bouton Img)

Non résolu.

> le code d'insertion d'une image du topoguide dans le forum ne fonctionne plus

Non résolu.

> Perte aussi du code (balise [ c ]), des spoilers (balise [ spoiler ]) et des couleurs (balise [ color ])

Résolu pour la balise color.

> un '+' en début de phrase est automatiquement remplacé par une puce, et donc tous les plussoiements "+ 1" sont cassés

Sans espace, '+1' fonctionne, donc pas si grave...

**Comment by arnaud-morvan** [comment]
Je tiens à préciser que nous n'avons implémenté dans discourse toutes les syntaxes permises par punbb dans la V5. Nous avons adapté le contenu pour qu'il s'affiche correctement avec la syntaxe de discourse.

> Visiblement, la syntaxe [ img=url ][ /img ] ne passe plus (i.e. celle utilisée depuis quelques temps via le bouton Img)

=> Il faut effectivement utiliser la syntaxe [img]url[/img]

> le code d'insertion d'une image du topoguide dans le forum ne fonctionne plus

Je ne suis pas au courant de ce type d'insertions, je vais me renseigner.

> Perte aussi du code (balise [ c ]), des spoilers (balise [ spoiler ]) et des couleurs (balise [ color ])

Les balises `[c]` et `[spoiler]` ne sont plus disponibles.

Lors de la migration, j'ai remplacé les `[c]` par des `[code]`.

et les `[spoiler]` par des`[details]`, ceci se base sur un plugin : https://github.com/discourse/discourse/tree/master/plugins/discourse-details

La balise `[color]` se base également sur un plugin : https://github.com/discourse/discourse-bbcode-color/

> un '+' en début de phrase est automatiquement remplacé par une puce, et donc tous les plussoiements "+ 1" sont cassés

A noter : J'ai aussi remplacé, lors de la migration, tous les "+ 1" en début de ligne par des "+1".

**Comment by asaunier** [comment]
> le code d'insertion d'une image du topoguide dans le forum ne fonctionne plus

@arnaud-morvan il s'agit de la syntaxe indiquée dans le champ "Code d'insertion dans le forum :" des documents images, par ex http://www.camptocamp.org/images/821742/fr/un-couche-de-soleil-de-malade#data `[img=1479113831_1579162882.jpg 821742 inline]un couché de soleil de malade[/img]`

Je doute que ca ait jamais marché dans Discourse !

**Comment by arnaud-morvan** [comment]
I've create a specific issue for this : #49

**Comment by jmarcmod** [comment]
@arnaud-morvan 

> Nous avons adapté le contenu pour qu'il s'affiche correctement avec la syntaxe de discourse.

OK j'ai vérifié, nickel !
Sauf pour :
[ img=url ][ /img ]
Certes, ça ne passe plus sur discourse, mais il n'y a pas eu de conversion, et du coup de nombreuses images V5 ne sont plus affichées, c'est dommage.

**Comment by arnaud-morvan** [comment]
Nous l'avons fait : 
https://github.com/c2corg/discourse/blob/fe94f084bcfdf2db32cc258de84f9e4238e0f523/script/import_scripts/punbb.rb#L688
Et j'ai même contrôlé que ça fonctionnait sur quelques exemples.

Mais je m'aperçois maintenant que ceci ne passe pas, car il y a du texte entre les balises : 

```
[img=http://www.runningwolfpack.com/potw/potw05_0410.jpg]Ysengrin[/img]
```

Lien V5 : 
http://www.camptocamp.org/forums/viewtopic.php?pid=101404#p101404

A noter : il est aisé d'afficher ce même post dans la V6, grâce aux permaliens créés par la migration : 
http://forum.demov6.camptocamp.org/viewtopic.php?pid=101404#p101404

Je vais fixer cela, et nous perdrons le titre de l'image.

**Comment by jmarcmod** [comment]
> Mais je m'aperçois maintenant que ceci ne passe pas, car il y a du texte entre les balises

Effectivement, mes tests portaient sur des images à titre.

> Je vais fixer cela, et nous perdrons le titre de l'image.

Parfait ! La perte du titre n'est vraiment pas grave.

**Comment by stef74** [comment]
On peut clore ?

**Comment by jmarcmod** [comment]
Arnaud doit encore supprimer le titre des images V5 :

> Je vais fixer cela, et nous perdrons le titre de l'image.

C'est donc à lui de dire si on peut fermer (le reste est OK).

**Comment by arnaud-morvan** [comment]
J'ai mis une étiquette "ready for démo".
J'ai fait une migration complète qui est en train de se terminer.
On pourra donc contrôler que tout est bon sur la démo cette semaine.

**Comment by jmarcmod** [comment]
**Migration du 28/11**
C'est OK maintenant pour les images avec titre (le titre est enlevé, l'image s'affiche).
