### ISSUE TITLE
Abonnements

### ISSUE THREAD

**Issue by fjacon** [c2corg/v6_forum#34]
Abonnements : ils ont désormais théoriquement migré, mais à vérifier pour ceux qui sont concernés (ce n'est pas mon cas).

NB : j'ai l'impression qu'on est par défaut également abonné à tous les sujets qu'on a créés (abonné sur Discourse = mode "Surveiller") ; c'est un peu lourd, à supprimer si possible.

**Comment by arnaud-morvan** [comment]
Concernant les subscription dans punbb, il existe une table punbb_subscriptions, simple relation entre topic et user. Je suppose donc que si l'enregistrement existe c'est que l'utilisateur est abonnée au topic.

Concernant les notifications, dans discourse, il existe 4 niveaux de notifications :
- 3 : Watching : You will be notified of every new reply in this topic, and a count of new replies will be shown.
- 2 : Tracking : A count of new replies will be shown for this topic. You will be notified if someone mentions your @name or replies to you.
- 1 : Normal : You will be notified if someone mentions your @name or replies to you.
- 3 : Muted : You will never be notified of anything about this topic, and it will not appear in latest.

J'observe que par défaut, le niveau de notification du createur du topic est 3 (watching) et 2 pour les utilisateur ayant posté une réponse.

Je ne vois rien dans la procédure d'import concernant les Abonnements / Notifications.
Je ne vois d'ailleurs aucune methode concernant les notifications dans la classe de base pour l'import.

**Comment by jmarcmod** [comment]
> J'observe que par défaut, le niveau de notification du createur du topic est 3 (watching) et 2 pour les utilisateur ayant posté une réponse.

A la réflexion ce mode de fonctionnement, auquel nous ne sommes pas habitués, est intéressant.
Cela responsabilise celui qui poste et encore plus celui qui ouvre un topic : si d'autres réagissent à son écrit, il le saura et se trouvera obligé d'aller voir, et le cas échéant d'expliquer ou de temporiser ses propos... Après libre à lui de baisser le niveau après coup.

**Comment by jmarcmod** [comment]
La migration des abonnements V5 (mode watching) est abandonnée, car trop compliquée, pour trop peu de cas (en effet seuls sont concernés les abonnements V5 pour des sujets qu'on n'a pas initiés, sinon c'est le mode watching par défaut).

On peut donc fermer cette issue.

**Comment by arnaud-morvan** [comment]
Nous avions abordé le fait de supprimer tous les abonnements (notifications) créés lors de la migration (par exemple le créateur du topic est abonné).
Il suffit de faire : 
```
UPDATE topic_users SET notification_level = 1;
```
Est toujours d'actualité ?

**Comment by arnaud-morvan** [comment]
@stef74 @jmarcmod @fbunoz : un avis ?

**Comment by jmarcmod** [comment]
Je n'ai pas pas tout compris ce qu'il était techniquement possible de faire.
Mais l'idée c'est :
- abandon des abonnements souscrits sous la V5 (ces abonnements étaient d'ordre volontaire) ;
- sur discourse, mode watching par défaut pour tous les sujets qu'on a créés sur la V5.
NB : le forum est déjà configuré pour que le mode watching soit le mode par défaut pour les sujets qu'on a initiés, mais a priori ça ne marche que pour les sujets postés en V6 ; il s'agirait donc d'étendre ce mode aux sujets V5 (pour leurs auteurs uniquement).

**Comment by arnaud-morvan** [comment]
Pour les données migrées de la V5, la règle semble être la suivante est la suivante : 

Pour les sujets :
- Le créateur du sujet est en Watching (Abonné)
- Les personnes qui ont répondu sont en Tracking (Suivi - Le nombre de nouvelle réponse est affiché pour ce sujet)

Pour les catégories : 
Par de règles définies, il semble tout de même que certains utilisateur aient placé les categories "Commentaires" et "Bistrot" en muté, sur datamigration, je suis un peut étonné.

J'en conclu qu'il ne faut rien faire.

**Comment by jmarcmod** [comment]
> Pour les données migrées de la V5, la règle semble être la suivante est la suivante

Parfait : on ne touche à rien.

> il semble tout de même que certains utilisateur aient placé les categories "Commentaires" et "Bistrot" en muté, sur datamigration

Je crois que c'est Bubu qui l'a fait par défaut, mais à titre expérimental.
On va sans doute l'enlever.
