### ISSUE TITLE
Forums privés

### ISSUE THREAD

**Issue by fjacon** [c2corg/v6_forum#35]
Forums privés : ils n'apparaissent pas dans les catégories ; mais les discussions de ces forums sont bien présentes ! A corriger, car pour l'instant c'est ingérable (on ne sait pas où aller, ni même où on est...)

**Comment by arnaud-morvan** [comment]
@jmarcmod : Je ne suis pas sur de bien comprendre ce que sont les "Forums privés".
Je vois dans Discourse des forums avec un cadenas, est-ce cela dont il s'agit ? Car je ne vois pas de problème sur ce point.
Peux-tu me donner le titre d'un des forums concernés ?

**Comment by jmarcmod** [comment]
@arnaud-morvan : les forums privés sont les forums réservés à une catégorie particulière de membres : forums réservés aux modérateurs, forums réservés aux membres de Camptocamp-Association, forums réservés aux membres du CA.
Ça n'a rien à voir avec les forums avec icône cadenas, prédéfinis par Discourse.
Par exemple cette discussion, importée de la V5 :
http://c2corgv6-discourse.demo-camptocamp.com/t/signalement-des-petites-moderations/70549
devrait se trouver dans le forum "Modos Forum", qui est privé et réservé aux modérateurs.
Mais aucun forum ni catégorie ne lui est attaché, et du coup on ne peut pas le trouver via l'index des catégories et forums :
http://c2corgv6-discourse.demo-camptocamp.com

Bref, j'ai l'impression que si les discussions des forums privés ont bien migré de V5 à V6, il y a eu perte des forums privés les contenant, autrement dit ces discussions sont devenues orphelines.

**Comment by arnaud-morvan** [comment]
En tant qu'admin, tout semble correct.

J'ai créé un compte modérateur : 
- Je vois bien la discussion comme orpheline.
- Sur la page d'accueil, je n'ai pas Administration des sites.
- http://c2corgv6-discourse.demo-camptocamp.com/c/administration-des-sites => Oops! Cette page n'existe pas ou est privée.
- http://c2corgv6-discourse.demo-camptocamp.com/c/administration-des-sites/modos-forum => :( Erreur lors d'une tentative de chargement

Coté permissions, je vois que : 
- administration-des-sites ne dispose d'aucun droits configurés
- modos-forum : moderateurs peut… Créer / Répondre / Voir

Il s'agit donc d'un problème de droits apparemment, je vais introspecter dans la base V5 et la procédure d'import.

**Comment by fbunoz** [comment]
Si, les forums privés sont bien les forums avec un cadenas.
En fait, dès qu'un forum n'est pas accessible à tous, il est affiché avec
un cadenas.
Attention, les droits des forums ne sont pas migrés automatiquement (seul
les groupes d'utilisateurs le sont en partie), c'est moi qui les ai
modifié, mais j'ai fait le minimum, il ne faut pas essayer de comparer les
droits exactement avec la V5.

Perso je ne vois pas de problème, la discussion que tu as donné en lien est
bien dans le forum "modo forum". Mais je suis admin.
Mais en tant qu'admin, je peux m'incarner dans ton compte. Et j'ai pu voir
que ça fonctionne bien : il y a bien les catégories de la discussion sous
le titre de la discussion.

**Comment by arnaud-morvan** [comment]
Oui, cela s'affiche bien depuis que j'ai ajouté les droits pour les modérateurs sur la catégorie parent Administration des sites.

J'ai mis du temps a bien comprendre ce que faisait la migration en termes de permissions.
Et effectivement tous les groupes ne sont pas migrés car vous ne pouviez pas affecter plusieurs groupes à un même utilisateur dans PunBB.

Sauf erreur de ma part, il est donc prévu, concernant la migration du forum :
1. de faire une première migration des données, dont la structure (groupes, catégories) et le gros des données (utilisateurs, topics et posts).
2. que les administrateurs définissent précisément les permissions des groupes sur les catégories
3. que nous fassions un second import (incrémental) pour la mise en production avec les derniers utilisateurs, topics et posts.

**Comment by arnaud-morvan** [comment]
@fbunoz : you said that restrictions are not setted on subcategories : 
https://github.com/c2corg/v6_forum/issues/24#issuecomment-222813461
This is in the scope of this issue.
And it seems that this is a TODO before first migration.

**Comment by jmarcmod** [comment]
> Oui, cela s'affiche bien depuis que j'ai ajouté les droits pour les modérateurs sur la catégorie parent Administration des sites.

Je confirme que désormais ça marche parfaitement !

> Si, les forums privés sont bien les forums avec un cadenas.

OK, maintenant je peux le constater.

**Comment by fbunoz** [comment]
> you said that restrictions are not setted on subcategories : #24 (comment)
> This is in the scope of this issue.

Yes, I forgot this part of the migration.

**Comment by arnaud-morvan** [comment]
I will just start working on, not a big deal.

**Comment by jmarcmod** [comment]
Le forum "comments", qui permet la gestion des commentaires de documents du topoguide, est bien présent, mais il n'apparait pas dans l'index catégories/forums de la home de Discourse ; un oubli ?
C'est en principe un forum privé (visible uniquement par les modos forum et les membres de l'assoce).

**Comment by arnaud-morvan** [comment]
Je vois dans le script d'import que cette catégorie (Commentaires du topoguide) est retirée de la page d'accueil. Je vais aussi le mettre en privé lors de la migration. Comme je l'ai annoncé un peu plus haut, certains réglages (notamment les permissions) pourront se faire manuellement dans discourse après la première migration.

**Comment by jmarcmod** [comment]
> Je vais aussi le mettre en privé lors de la migration.

Après tests sur le topoguide, je crois qu'il ne faut pas mettre ce forum en privé ; le mode de fonctionnement des commentaires a changé : on les rédige directement dans Discourse, donc comme tout membre doit pouvoir commenter, "comments" doit rester accessible à tous, en lecture comme en écriture.

@fbunoz : tu confirmes ?

**Comment by arnaud-morvan** [comment]
Pour pouvoir poster depuis le topoguide, il faut être connecté.

**Comment by jmarcmod** [comment]
On est d'accord. Quand je disais "à tous", je pensais aux membres lambda connectés (par opposition aux modos).

**Comment by arnaud-morvan** [comment]
Voici ce que j'obtiens pour les restrictions à la sortie du script : 

```
restricted forums (28):
3: Modos Ecotourisme
27: Le Site : suggestions, bugs et problèmes
28: Modération : forums, topoguide, articles
31: Actualités : Site et Association
33: Discussions au sein de l'Association
34: Conseil d'Administration de l'Association
35: Assemblée Générale de l'Association
36: Modos Forum
37: Modos Topoguide
38: Articles
39: Traduction
40: Développement
73: Archives Modération Forums
74: Purgatoire
84: Poubelle
95: Commission Publicité
102: V6 - BD incidents & accidents
103: V6 - Encyclopédie
104: V6 - Réseau social & Forum
105: V6 - Topoguide
106: V6 - Ergonomie & design
107: V6 - Mobilité
108: V6 - Architecture & technos
109: V6 - API & Echanges avec les sites partenaires
110: V6 - Communication & Traduction
111: V6 - Petites annonces & Actus
112: V6 - Vie et organisation du projet
113: V6 - Financement

public forums: (72):
1: Comments
2: Conditions : Neige et Avalanches
4: Destinations lointaines / Expéditions
5: Conditions : Alpinisme et Cascade de glace
6: Conditions : Randonnée pédestre
7: Techniques et Matériel : Ski, Surf, Raquette
8: Techniques et Matériel : Glace, Neige, Mixte
9: Techniques et Matériel : Randonnée et Multiactivité
10: Techniques et Matériel : Rocher, SAE
11: Médecine des sports de montagne, Entraînement
12: Annonces matos Ski, Surf, Raquette
13: Annonces matos Glace, Neige, Mixte
14: Annonces matos Rocher, SAE
15: Annonces matos Divers (multiactivité, sacs, vêtements, orientation, livres...)
16: Autres annonces (gîtes, locations, fourgons...)
17: Annonces de Professionnels
18: Actualités : Multiactivité
19: Partenaires ++
20: Discussions Ski, Surf, Raquette
21: Discussions Alpinisme et Cascade de glace
22: Discussions Escalade
23: Discussions Randonnée pédestre, Trail
24: Discussions générales
25: Récits / Photos / Vidéos
26: Bistrot
41: Condizioni / meteo
42: Mobilité douce
43: Condizioni : Arrampicata e escursionismo
44: Condizioni : Alpinismo e cascata di ghiaccio
46: Professionali
47: Compro - Vendo
48: Attualità / Eventi
49: Compagno cercasi
50: Discussione varie sulla montagna
51: "Al bar"
53: Moderatori (accesso limitato)
58: Skitouring
59: Rock-climbing
60: Mountaineering
61: Skitouren
62: Klettern
63: Bergsteigen
64: Esquí de montaña
65: Escalada
66: Alpinismo
67: Esquí de muntanya
68: Escalada
69: Alpinisme
70: Sito web
71: Attualità : sito web e associazione
72: Tecnica e materiale
75: Partenaires : Ski, Surf, Raquette, Randonnée, Trail
76: Partenaires : Escalade, SAE
77: Co-voiturage
78: Perdu / trouvé
79: Conditions : Escalade
80: Eskia
81: Alpinismoa
83: Eskalada
85: Actualités : Ski, Surf, Raquette
86: Actualités : Alpinisme et Cascade de glace
87: Actualités : Escalade
89: Actualités : Randonnée pédestre, Trail
90: News / Events
91: Aktuelles / Ereignisse
92: Noticias / Eventos
93: News / Events
94: News / Events
96: Partenaires : Alpinisme, Cascade de glace
99: Discussions Parapente montagne
100: Actualités : Parapente montagne
101: Techniques et Matériel : Parapente montagne
```

**Comment by fbunoz** [comment]
Le mode de fonctionnement n'a pas changé, c'est pareil sur la v5.
J'ai rendu la sur - catégorie invisible sauf pour l'association, et le
forum comments visible par tout le monde, mais il est inaccessible sauf
pour l'assoce malgré tout.
A voir si ça n'a pas cassé les commt dans le topoguide (visiblement non,
mais à tester).

**Comment by jmarcmod** [comment]
> Le mode de fonctionnement n'a pas changé, c'est pareil sur la v5.

Ah oui c'est moi qui fatigue...

**Comment by jmarcmod** [comment]
@arnaud-morvan 

> Voici ce que j'obtiens pour les restrictions à la sortie du script

Attention, 4 forums de la catégorie "Site et Association" sont en fait publics :
   27: Le Site : suggestions, bugs et problèmes
   28: Modération : forums, topoguide, articles
   31: Actualités : Site et Association
   39: Traduction

@fbunoz  : il serait peut-être pertinent de scinder cette catégorie en 2 ?
Genre laisser "Site et Association" pour les 4 forums publics, et créer "Association en interne" pour les 4 forums privés (33, 34, 35, 40) ?

**Comment by arnaud-morvan** [comment]
Je merge ma modification, si besoin nous ferons un ajustement avant la migration.

**Comment by jmarcmod** [comment]
Je suis modo sur la version beta, mais je n'ai accès à aucun forum privé... alors que j'y avais accès sur l'ancienne version.

**Comment by asaunier** [comment]
La migration ne restaure pas les droits d'accès aux forums privés il me semble. Il faut qu'un admin (Bubu) te remette les droits à la main.

**Comment by jmarcmod** [comment]
Exact Alex, Bubu m'a remis les droits, et maintenant c'est tout bon !

**Comment by jmarcmod** [comment]
@arnaud-morvan : en plus des 4 forums qui sont publics et non privés (27, 28, 31, 39), il y a aussi un forum privé et non public :
53: Moderatori (accesso limitato)
Sur l'actuelle beta, une seule correction a été faite : 27 est passé en public.
**Reste à passer 28, 31, 39 en public, et à passer 53 en privé.**

@fbunoz : je réitère ma proposition de scinder la catégorie "Site et Association" en deux (une catégorie publique, une catégorie privée) ; souvent, des modos ou des adhérents de l'assoce se trompent et postent sur les forums publics ce qu'ils croient être des messages internes... En plus ça permet d'avoir le cadenas bien explicite sur les catégories 100% privées.
Ça pourrait donner :
- Site et Association (31/27/28/39)
- Association en interne (33/40/35/34)
  On pourrait faire la modif dès maintenant sur la V5, avant migration (en mettant le forum Traduction en fin de catégorie, car moins important que les 3 autres).

**Comment by arnaud-morvan** [comment]
Il a été convenu que nous laisserions le soin à l'association de fixer les droits sur les catégories après la migration initiale.

**Comment by jmarcmod** [comment]
> scinder la catégorie "Site et Association" en deux (une catégorie publique, une catégorie privée)

Fait par fbunoz hier.

> Il a été convenu que nous laisserions le soin à l'association de fixer les droits sur les catégories après la migration initiale.

OK.
On peut donc fermer cette issue.
