### ISSUE TITLE
Images fraichement insérées 

### ISSUE THREAD

**Issue by fjacon** [c2corg/v6_forum#37]
Images fraichement insérées : un script automatique (de redimensionnement des images ?) semble modifier a posteriori les balises et du coup fait disparaitre l'affichage des images (pourtant visibles lors de la mise en ligne).

**Comment by fjacon** [comment]
et aussi : 

Avatars : la saisie d'un avatar ne fonctionne plus : l'image se télécharge, mais "sauvegarder les modifications" ne sauvegarde rien.

**Comment by arnaud-morvan** [comment]
J'ai fait quelques tests, je n'ai pas réussi à reproduire.

**Comment by stef74** [comment]
Je propose de clore ... la beta confirmera si il y un soucis.

2016-10-20 13:45 GMT+02:00 Arnaud Morvan notifications@github.com:

**Comment by jmarcmod** [comment]
C'est nickel sur la beta !
OK pour clore.
