### ISSUE TITLE
Citations

### ISSUE THREAD

**Issue by fjacon** [c2corg/v6_forum#38]
2 soucis lorsque la citation pointe vers une autre discussion (comme pour la migration, à une nuance près cf le lien d'échec) :

```
on récupère le message source via le bouton '->', mais les 2 liens vers ce message, avec nom de la discussion mère, sont bugués ; exemple : http://c2corgv6-discourse.demo-camptocamp.com/t/test-citations/169440/2 (lien http://c2corgv6-demo.gis.internal/t/test-liens/169436/4 ouvrant une page d'échec de connexion) ;
l'auteur du message source n'apparait pas toujours, même avec le bouton 'v', pour le connaitre il faut en général revenir au message source.
```

**Comment by jmarcmod** [comment]
Il semble que cette issue, concernant la navigation V6, et la première partie de l'[issue #32](url=https://github.com/c2corg/v6_forum/issues/32) concernant la migration V5-V6, pointent sur un seul et même problème.

**Comment by arnaud-morvan** [comment]
Duplicated, closing
