### ISSUE TITLE
Localization for discourse

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_forum#4]
Could you add localization FR,IT,DE,ES for discourse ?

I don't know if localization is defined on user level or forum level. It's seem theye have per-user-locale site setting.

For C2C association test it's better french is enable.

**Comment by asaunier** [comment]
I wonder what we can do to make sure the discourse interface is loaded with the lang previously used by the user in the UI and if it is possible to change the interface lang by some link in the header (as in the UI), not only in the users' preferences.

**Comment by tsauerwein** [comment]
Can we change the user language using the Discourse API, @gberaudo?

**Comment by gberaudo** [comment]
It is possible to choose the default localization and allow user localization in discourse admin page.
There is a `lang` attribute in the `html` tag but it does not match the chosen language. After selecting
Deutsch the attribute is `fr` (the default language)...

Unfortunately, using the Discourse API, even if available, would not work for visitors without account or logged out.
- Discussion about switching language through an URL parameter (not implemented in Discourse):
  https://meta.discourse.org/t/switch-language-via-url/28937/3
- It would also be necessary to detect the language of the page to adapt the language of the custom header menu. See https://meta.discourse.org/t/detecting-user-language/40505. The chosen language is available in `I18n.locale`.
- A discourse plugin to detect the language using the http header https://github.com/scossar/accept-language.

**Comment by gberaudo** [comment]
@stef74, I have added the accept-language plugin to http://c2cpc34.camptocamp.com:3000/admin/plugins. The plugin will automatically detect the language of the browser and adapt the forum language, even when the user is not connected.

**Comment by stef74** [comment]
I have stack trace error messsage ...
No route matches [GET] "/admin/plugins"

2016-03-04 16:38 GMT+01:00 gberaudo notifications@github.com:

**Comment by gberaudo** [comment]
You must be connected as admin to access the plugins list and configuration.
