### ISSUE TITLE
Protecting the demo forum with a password?

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_forum#40]
The UI demo is password-protected whereas the demo discourse instance is not. Perhaps we should apply the same protection to it as well (with the same username/password)?

**Comment by gberaudo** [comment]
Adding a password would prevent the API to communicate with Discourse. Is there a simple way to prevent google from indexing the forum?

**Comment by tsauerwein** [comment]
Could we use an internal (unprotected) address of the forum for the API?

**Comment by gberaudo** [comment]
Indeed, it is a possibility.
I checked Discourse, it is currently configured to not allow indexing by search engines so it may be a non-issue. See http://c2corgv6-discourse.demo-camptocamp.com/admin/site_settings/category/security

**Comment by asaunier** [comment]
I know that @fbunoz has changed the "robots.txt" of the demo forum using the admin interface. It should now be marked as "ino index". So adding a basic auth adds too much complexity, we can probably live with the current setting.

> Could we use an internal (unprotected) address of the forum for the API?

Like the internal API URL for the UI server side?
Anyway that would make sense (for security and performances reasons?) to use an internal URL to make the API and forum exchange, wouldn't it?
