### ISSUE TITLE
Menu on discourse forum

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_forum#41]
@ginold said in issue https://github.com/c2corg/v6_ui/issues/461

> I have created 2 different styles for the menu on discourse forum page.
> One with menu on the top, like on ubuntu.discrouse :
> http://c2corgv6-discourse.demo-camptocamp.com/?preview-style=1e6de3bd-3b54-41f3-966c-b9b1c93d4648
> 
> And the second which is more c2corg.v6-like, but I stopped going further because I dont' know how to import CSS classes and SVG icons into discourse, so any glitches are normal.
> http://c2corgv6-discourse.demo-camptocamp.com/?preview-style=7d20cade-645c-46d8-8956-de59416683ef
> 
> I would stick to the first one, it is much more easily maintainable.
> BTW how to import generated links if I don't want to hardcode them? like the URLs of the links in the menus with request.static_url....

**Comment by stef74** [comment]
@ginold the vertical menu is cleary the good choice. The goal is to have the forum embedded in c2c.org v6.
The defaut of actual vertical menu is to have discourse menu on the top and if you switch between topoguide and forum menu item are not aligned. 

Disourse have good community ... use it ;-)

**Comment by asaunier** [comment]
What about this issue?
I think we have no menu ready for the forum!?

**Comment by ginold** [comment]
I remember i had started working on a menu for discourse and had a prototype but i can't see where it has gone

**Comment by asaunier** [comment]
> I remember i had started working on a menu for discourse and had a prototype but i can't see where it has gone

Was it only available in the old discourse demo? Or was it saved somewhere in this repo (branch?)?
Everything that is only saved in a discourse instance is not permanent and can be deleted at any time. Permanent config/content should be saved in the repo.

**Comment by ginold** [comment]
I can't remember, I can't tell if it has even been used on discourse at the end, but i cant find any branch either - which is even more strange. Maybe I copied it to discourse and deleted the branch.

**Comment by jmarcmod** [comment]
Pour être en phase avec les pages topoguide, il vaut mieux un menu vertical à gauche.
Mais pour l'instant nous n'avons pas de menu... en particulier, on ne peut pas revenir au topoguide depuis le forum.

**Comment by fjacon** [comment]
@gberaudo avait fait quelque chose, qui reste à personnaliser.

**Comment by asaunier** [comment]
Same question: where?

**Comment by gberaudo** [comment]
You can find the code in the initial issue: https://github.com/c2corg/v6_forum/issues/2.

**Comment by fbunoz** [comment]
Be careful when testing the design : if we want to use the same code for desktop and mobile, it must be copied to two places in the admin interface (a mobile picto allows to switch between destop code and mobile code).

**Comment by stef74** [comment]
When Its ready ?

**Comment by jmarcmod** [comment]
**Migration du 28/11**
A venir j'imagine ? car ne concerne pas la migration.

**Comment by stef74** [comment]
Juste test on safari ... is Ok but little issue on mobile the "hamburger" is not same and the order in topoguide is Hamburger / Logo , in discourse Logo / hamburger.

Probably to close this issue and reopen it with less priority.

**Comment by stef74** [comment]
bug report : #56

**Comment by fbunoz** [comment]
Please, don't remove the "design v6" CSS in the Discourse admin on the demo, as it is the design for the forum (without menu), that the association is going to dev.
I saved the CSS, but to allow testing the design by the association, it must be used on the demo.

**Comment by ginold** [comment]
I brought them back (i don't have the names anymore -> it's css1, css2).

**Comment by mgerbaux** [comment]
Menu is not available on small screen ; https://forum.camptocamp.org/t/v6-sur-android/173318
(and camptocamp logo does not link to anything)

**Comment by desnoes** [comment]
@mgerbaux : the bug has been fixed or is it still there ?
