### ISSUE TITLE
Duplicated guidebook related topics

### ISSUE THREAD

**Issue by arnaud-morvan** [c2corg/v6_forum#42]
Here is a request to get duplicated topics from discourse:

```
SELECT *
        FROM (
            SELECT
                id,
                title,
                category_id,
                count(id) OVER (PARTITION BY title) AS duplicate_count
            FROM topics
            WHERE deleted_at IS NULL AND category_id = 28
            ORDER BY title
        ) AS qualified_topics
        WHERE duplicate_count > 1
```

And the result is : 

id;title;category;duplicate_count
68518;"107473_fr";28;2
68519;"107473_fr";28;2
68572;"107568_fr";28;2
68573;"107568_fr";28;2
71686;"115858_it";28;2
71685;"115858_it";28;2
74256;"124815_fr";28;2
74258;"124815_fr";28;2
74264;"124833_fr";28;2
74265;"124833_fr";28;2
74447;"125133_fr";28;2
74446;"125133_fr";28;2
83419;"142778_fr";28;2
85247;"142778_fr";28;2
82130;"145334_fr";28;2
82131;"145334_fr";28;2
82612;"146737_fr";28;2
82613;"146737_fr";28;2
83495;"151802_fr";28;2
83496;"151802_fr";28;2
83800;"152872_fr";28;2
83799;"152872_fr";28;2
84607;"156577_fr";28;2
84601;"156577_fr";28;2
85264;"159707_fr";28;2
85265;"159707_fr";28;2
85390;"160425_fr";28;2
85391;"160425_fr";28;2
87099;"168267_fr";28;2
87095;"168267_fr";28;2
87132;"168465_fr";28;2
87133;"168465_fr";28;2
125475;"172603_fr";28;2
125474;"172603_fr";28;2
88685;"173359_fr";28;2
88684;"173359_fr";28;2
90254;"180051_fr";28;2
90253;"180051_fr";28;2
90365;"180737_fr";28;2
90366;"180737_fr";28;2
91241;"185039_fr";28;2
91243;"185039_fr";28;2
92990;"191342_fr";28;2
92989;"191342_fr";28;2
94742;"196377_fr";28;2
94741;"196377_fr";28;2
94636;"196693_fr";28;2
94634;"196693_fr";28;2
95145;"198934_fr";28;2
95148;"198934_fr";28;2
95726;"201693_it";28;2
95727;"201693_it";28;2
95752;"201793_fr";28;2
95753;"201793_fr";28;2
96017;"203039_fr";28;2
96016;"203039_fr";28;2
96518;"205375_fr";28;2
96517;"205375_fr";28;2
98009;"212069_fr";28;2
98008;"212069_fr";28;2
98426;"214174_fr";28;2
98425;"214174_fr";28;2
98897;"216884_fr";28;2
98896;"216884_fr";28;2
99453;"219065_fr";28;2
99454;"219065_fr";28;2
101176;"225687_fr";28;2
101177;"225687_fr";28;2
125582;"227527_fr";28;2
125583;"227527_fr";28;2
101556;"227717_fr";28;2
101557;"227717_fr";28;2
102154;"231117_fr";28;2
102155;"231117_fr";28;2
102278;"231728_fr";28;2
102279;"231728_fr";28;2
103168;"236558_fr";28;3
103170;"236558_fr";28;3
103169;"236558_fr";28;3
103987;"240950_fr";28;2
103988;"240950_fr";28;2
105112;"244345_fr";28;2
105113;"244345_fr";28;2
106739;"250866_fr";28;2
106738;"250866_fr";28;2
124769;"254412_fr";28;2
124768;"254412_fr";28;2
108228;"259349_it";28;2
108227;"259349_it";28;2
108351;"260326_fr";28;2
108350;"260326_fr";28;2
108582;"261673_fr";28;2
108581;"261673_fr";28;2
108959;"264340_fr";28;2
108960;"264340_fr";28;2
109103;"265219_fr";28;2
109102;"265219_fr";28;2
109188;"265508_fr";28;2
109186;"265508_fr";28;2
110014;"270443_fr";28;2
110013;"270443_fr";28;2
110850;"275414_fr";28;2
110852;"275414_fr";28;2
111390;"277684_fr";28;2
111391;"277684_fr";28;2
112834;"285057_fr";28;2
112872;"285057_fr";28;2
113005;"285906_fr";28;2
113006;"285906_fr";28;2
113474;"289203_fr";28;2
113475;"289203_fr";28;2
113574;"290037_fr";28;2
113573;"290037_fr";28;2
114094;"294418_fr";28;2
114095;"294418_fr";28;2
115033;"301260_fr";28;2
115034;"301260_fr";28;2
115196;"302192_fr";28;2
115195;"302192_fr";28;2
115542;"304597_fr";28;2
115543;"304597_fr";28;2
115704;"305377_fr";28;2
115705;"305377_fr";28;2
116064;"307384_fr";28;2
116082;"307384_fr";28;2
116405;"309181_fr";28;2
116406;"309181_fr";28;2
116479;"309663_fr";28;2
116478;"309663_fr";28;2
117748;"316284_fr";28;2
117749;"316284_fr";28;2
118237;"319016_it";28;2
118236;"319016_it";28;2
118328;"319811_fr";28;2
118329;"319811_fr";28;2
118475;"320921_fr";28;2
118474;"320921_fr";28;2
119586;"327166_fr";28;2
119585;"327166_fr";28;2
119931;"329591_fr";28;2
119930;"329591_fr";28;2
120636;"334641_fr";28;2
120635;"334641_fr";28;2
121120;"337755_fr";28;2
121121;"337755_fr";28;2
123139;"350407_fr";28;2
123138;"350407_fr";28;2
123473;"352528_fr";28;2
123474;"352528_fr";28;2
125087;"362577_fr";28;2
125086;"362577_fr";28;2
126060;"371295_fr";28;2
126059;"371295_fr";28;2
126251;"372296_fr";28;2
126252;"372296_fr";28;2
127336;"379331_fr";28;2
127335;"379331_fr";28;2
127366;"379579_fr";28;2
127365;"379579_fr";28;2
127757;"381844_fr";28;2
127758;"381844_fr";28;2
128752;"387226_it";28;2
128753;"387226_it";28;2
128821;"387681_fr";28;2
128822;"387681_fr";28;2
128892;"388063_it";28;2
128891;"388063_it";28;2
129121;"389412_fr";28;2
129122;"389412_fr";28;2
129525;"392479_fr";28;2
129523;"392479_fr";28;2
129606;"393106_it";28;2
129607;"393106_it";28;2
129873;"395721_fr";28;2
129874;"395721_fr";28;2
129927;"396367_fr";28;2
129929;"396367_fr";28;2
131350;"408034_it";28;2
131349;"408034_it";28;2
132544;"419115_fr";28;2
132543;"419115_fr";28;2
132598;"419539_fr";28;2
132599;"419539_fr";28;2
133198;"424431_fr";28;2
133202;"424431_fr";28;2
133858;"430205_fr";28;2
133856;"430205_fr";28;2
134355;"433766_fr";28;2
134356;"433766_fr";28;2
134579;"435458_fr";28;2
134581;"435458_fr";28;2
134701;"436560_fr";28;2
134702;"436560_fr";28;2
135183;"440545_fr";28;2
135184;"440545_fr";28;2
135641;"444649_it";28;2
135642;"444649_it";28;2
135835;"446672_fr";28;2
135834;"446672_fr";28;2
137315;"461050_fr";28;2
137316;"461050_fr";28;2
137398;"461901_fr";28;2
137397;"461901_fr";28;2
138293;"468453_fr";28;2
138292;"468453_fr";28;2
138397;"469324_fr";28;2
138398;"469324_fr";28;2
138528;"470005_fr";28;2
138531;"470005_fr";28;2
140580;"487153_fr";28;2
140579;"487153_fr";28;2
141147;"491447_fr";28;2
141145;"491447_fr";28;2
141300;"492975_fr";28;2
141299;"492975_fr";28;2
141525;"494976_fr";28;2
141526;"494976_fr";28;2
141903;"499727_fr";28;2
141902;"499727_fr";28;2
142111;"502096_fr";28;2
142110;"502096_fr";28;2
142676;"508300_fr";28;2
142674;"508300_fr";28;2
142851;"510527_fr";28;2
142850;"510527_fr";28;2
143225;"514805_fr";28;2
143226;"514805_fr";28;2
143744;"521791_fr";28;2
143745;"521791_fr";28;2
143888;"523791_fr";28;2
143889;"523791_fr";28;2
144172;"527345_fr";28;2
144177;"527345_fr";28;2
144365;"529018_fr";28;2
144366;"529018_fr";28;2
144582;"531174_fr";28;2
144581;"531174_fr";28;2
144579;"531443_fr";28;2
144578;"531443_fr";28;2
145147;"536656_fr";28;2
145148;"536656_fr";28;2
125649;"53800_fr";28;2
125651;"53800_fr";28;2
147946;"565667_fr";28;2
147957;"565667_fr";28;2
100782;"56956_fr";28;2
100783;"56956_fr";28;2
149912;"584018_it";28;2
149914;"584018_it";28;2
114980;"99080_fr";28;2
114981;"99080_fr";28;2
71779;"Itinerario";28;2
71780;"Itinerario";28;2

**Comment by arnaud-morvan** [comment]
@asaunier : Can you ping an administrator about this duplicated topics, note that this ids come from discourse (V6) database, but titles should permit to get correspondance in V5 forum.

**Comment by asaunier** [comment]
I am not sure to know what I should ask the association for!?

Where do these duplicated topics come from? Don't you think they have been duplicated by the migration script? Or you think they are already duplicated in the v5 forum?

What is "category = 28"? Is it related to http://www.camptocamp.org/forums/viewforum.php?id=28 ?

**Comment by arnaud-morvan** [comment]
We should verify that these topics are really duplicated in V5 or not. Where are store comments in V5, in forum ? I don't know about the V5 tools. Note that duplicated topics content differ.

Maybe I can add informations in query like document title, type and lang. For now titles are the V6 demo ones (discourse and v6_api / ui ones). This should be sufficient get the document page in V6 and the corresponding page in V5 guidebook and forum.

Note : The category id come from discourse, this should not be related to any V5 id.

**Comment by asaunier** [comment]
> Where are store comments in V5, in forum ?

Yes. So they are migrated to v6 using the forum migration script created by @gberaudo 
Are there duplicates in other categories (=standard forum categories)?

**Comment by asaunier** [comment]
By the way the v5 DB is also available on the dev server ("c2corg"). Perhaps you could run a similar query on its "punbb_topics" and figure out if there are also duplicates in the original DB?

**Comment by gberaudo** [comment]
The duplications seems to come from v5:

@arnaud-morvan, taking the first topic id from your list it is also duplicated in v5:

```
c2corg=# select id, posted from punbb_topics where subject = '107473_fr';
   id   |   posted   
--------+------------
 114679 | 1195060868
 114677 | 1195060797
```

There is a 1 hour difference between these two timestamps.

**Comment by fbunoz** [comment]
The duplications come from the v5 : 2 users post the first comment, which create 2 topics for the comments. Or an user come back to the post edit page and re-post the first comment.
They are not visible in the comment page (for reading, the duplicates don't cause any problem, they appear as a single topic), but they can be seen and merged with moderator right in the V5 forum.

I started to merge the duplicates in the V5 forum (using the list in the first post of this issue), but i think it would be better to merge the duplicate by the migrating script.

**Comment by arnaud-morvan** [comment]
It seems really complex and tricky to merge this topics in the migration script which is already complex.
If the V5 forum has such functionnality, IMHO it sounds reasonnable to merge them before migration.

**Comment by fjacon** [comment]
Yes I think the association should prepare a V5 database without duplicates.
Is this OK ?

**Comment by fbunoz** [comment]
> Yes I think the association should prepare a V5 database without duplicates.
> Is this OK ?

It is possible, but it takes 2-3 weeks of work (with few work per day : manually, one merge take 1-2 min).
We need the list of duplicates for all Comments forum. I think the list given in the first post come from a partial dump of the V5 DB, because there should be some duplicates for doc ID > 600000.
More over, we'll need an update of this list just before the final migrating, to merge the duplicates created since the last list.

**Comment by asaunier** [comment]
> More over, we'll need an update of this list just before the final migrating, to merge the duplicates created since the last list.

It would be more relevant to create a similar SQL query directly for the v5 DB. Especially because importing the forum DB again takes days and we would need to make a new DB import (days again...) after the comment duplicates have been fixed.

**Comment by arnaud-morvan** [comment]
The request at the to of the issue is an Discourse one.
To get the V5 duplicates : 

```
SELECT
    subject,
    count(id),
    array_agg(id) AS topic_ids
FROM punbb_topics
WHERE forum_id = 1 
GROUP BY subject
HAVING count(id) > 1
```

**Comment by arnaud-morvan** [comment]
Note that there is a lot of duplicated topics (on subject) in other forums, but this is not as real problem for the link with the guidebook.

**Comment by arnaud-morvan** [comment]
We have found a simple solution to merge duplicated topics during migration, by fooling the migration script about the punbb_posts.topic_id.

I will apply this on topoguide comments for sure. The question is : should we do the same for other forums ?

**Comment by fbunoz** [comment]
> We have found a simple solution to merge duplicated topics during migration, by fooling the migration script about the punbb_posts.topic_id.

Good !

> should we do the same for other forums ?

No. Only the "Comments" forum has a link with the guidebook.
For the other forums, there isn't any link between the topics and the guidebook in the DB or in the guidebook code.
It is normal that there are duplicates in other forums. Some of them need to be merged, but it will be done by the moderators (this is only dummy topics, without any consequence).

**Comment by jmarcmod** [comment]
Les doublons ont été supprimés par les modos, avant la migration pour la beta.
Donc normalement, problème résolu !

**Comment by asaunier** [comment]
A part si de nouveaux doublons sont introduits d'ici à la migration finale. Dans la copie de la base v5 utilisée par la SA actuellement (vieilles de 2 ou 3 semaines), il reste 3 doublons (peut-être corrigés dans la v5 depuis ?) : 

```
  subject  | count |    topic_ids    
-----------+-------+-----------------
 689988_fr |     2 | {282180,282181}
 814137_fr |     2 | {297413,297414}
 814462_fr |     2 | {297438,297437}
```

**Comment by jmarcmod** [comment]
Pas corrigés, mais on va le faire très rapidement !

**Comment by jmarcmod** [comment]
> il reste 3 doublons

Corrigé !

@asaunier 
Tu penseras à me donner, disons 24h avant le blocage de la V5, la liste d'éventuels nouveaux doublons à supprimer.

**Comment by jmarcmod** [comment]
@stef74 : 
Issue à fermer stp.
