### ISSUE TITLE
No need for comments in profile pages

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_forum#47]
In v5 it's possible to add comments to a profile page. But it's not that relevant and often misused.

In v6, the association is OK for not having comments in the profile page. So I will simply skip this part in https://github.com/c2corg/v6_ui/pull/728

Of course it would then make sense not to migrate the existing profile comments to the discourse DB.
But I guess it's OK to migrate them and simply not use them.

@arnaud-morvan what do you think?

**Comment by arnaud-morvan** [comment]
I do not have any opinion on this.
In discourse it is possible to create extra user fields.

**Comment by stef74** [comment]
Whats happen if you do NOTHING on this subject (concerning current
comments) ? we have old comment post in forum database ...

2016-10-20 16:38 GMT+02:00 Arnaud Morvan notifications@github.com:

**Comment by asaunier** [comment]
They will be migrated but not used/shown, right?

**Comment by arnaud-morvan** [comment]
Sorry, misunderstood, we talk about topoguide comment topics.
Yes, they will be migrated, but no link in the UI.
Note that, during migration, concerning the document comments, we add a first posts, based on the category.
I don't see user comments, is it in the same category ?

**Comment by asaunier** [comment]
> I don't see user comments, is it in the same category ?

Yes, user pages are documents like others.

**Comment by arnaud-morvan** [comment]
So there should be a first post, may be with "Document not found" instead of link.
They will be migrated, shown or not, depending on rights set on parent categories. If I correctly remember, parent categories are public (to get correct breadcrumb) but not shown on home page.

**Comment by asaunier** [comment]
Do we really need to do something about this issue? If not, feel free to close it.

**Comment by jmarcmod** [comment]
Issue à fermer.
