### ISSUE TITLE
Tests sur smartphone

### ISSUE THREAD

**Issue by jmarcmod** [c2corg/v6_forum#50]
Je n'ai fait aucun test sur smartphone (je n'en ai pas !) mais catherine, de l'Association, en a fait beaucoup.
Elle les a rapportés dans le google doc ci-dessous (en lecture seule mais ouvert aux commentaires).
Je n'ai pas le temps d'en faire une synthèse, mais si jamais vous y voyez des problèmes qui relèvent de la SA, il est peut-être encore temps d'y remédier.
https://docs.google.com/document/d/1QO-EW_rrNLv2qxJrZjaXfFK_tul321olPjrC18YJ-4M/edit?usp=drive_web

**Comment by stef74** [comment]
Honnêtement la SA ne va éplucher votre Google doc ... merci de remonter les bugs directement dans le ticket avec une checkbox par point ( demander de l aide côté asso si besoin) ... idéalement valide avant avec bubu si c est pas des soucis de parametrage

**Comment by jmarcmod** [comment]
Je comprends.
Je vais transmettre par mail à Bubu, vu que c2c est en rade.
_Edit :_ fait ; mais c2c réparé, donc [sujet dédié](http://www.camptocamp.org/forums/viewtopic.php?id=298494)
