### ISSUE TITLE
Profil topoguide & Profil forum

### ISSUE THREAD

**Issue by jmarcmod** [c2corg/v6_forum#51]
Sur la V5, il y avait un seul profil, accessible en cliquant sur le pseudo topoguide depuis le topoguide, ou sur le pseudo forum depuis le forum ; ce profil contenait des liens vers les contributions au topoguide et vers les messages du forum, et était éditable pour y ajouter textes et photos.

Sur la V6, il y a 2 profils différents : 
+ le profil topoguide, accessible en cliquant sur le pseudo topoguide depuis le topoguide, reprend le concept du profil V5 (éditable), mais sans les messages du forum ;
+ le profil forum, accessible en cliquant (*) sur le pseudo forum depuis le forum, n'est pas éditable, il est généré automatiquement par discourse, et comprend plein de choses intéressantes sur les messages postés dans le forum (y compris les messages privés), mais il est totalement dissocié du topoguide.

_(*) Plus précisément, un clic gauche ne donne qu'un pop-up résumé ; pour le profil complet : clic droit + ouverture dans un nouvel onglet._

**On souhaiterait donc garder ces 2 profils, qui sont complémentaires, mais en y ajoutant 2 liens : 
-un lien vers le profil forum dans le profil topoguide ;
-un lien vers le profil topoguide dans le profil forum.**

NB : pour le profil topoguide, il y a dans le bloc _Informations_ une ligne _Pseudo forum: ***_ ; on pourrait rendre ce pseudo cliquable, ouvrant ainsi le profil forum.

Pour mieux comprendre, voici, sur la beta V6 :
-mon profil topoguide : http://www.demov6.camptocamp.org/profiles/9354/fr
-mon profil forum : http://forum.demov6.camptocamp.org/users/JeanMarc/summary

**Comment by stef74** [comment]
Merci de pas générer une issue pour ce type de demande mais éventuellement d ouvrir une discussion forum. Seul les demandes d évolution validés par la coordination/copil ( et discuter en interne) doivent être saisie

**Comment by jmarcmod** [comment]
@stef74 : tout le monde est désormais convaincu à l'Association de la nécessité de cette évolution.
Pourrait-on rouvrir l'issue en la mettant en 6.1 ?

NB : d'après Alex, le lien sur le profil topoguide est facile à faire ; la difficuté c'est le lien sur le profil forum, car sur discourse, l'ID c2c des contributeurs n'est pas dispo, on n'a donc que le pseudo topoguide pour rechercher le profil topoguide.

Par ailleurs un 3ème lien est demandé :
   **lien sur la page compte forum vers la page compte topoguide**
avec un intitulé du genre "pour modifier votre adresse mail ou vos pseudos".
Ceci afin de pouvoir facilement modifier e-mail et pseudos quand on est sur le form (ces 3 paramètres sont inertes sur la page compte forum).

Page compte forum : http://forum.demov6.camptocamp.org/users/***/preferences (labellisée "Préférences")
_(remplacer *** par son pseudo forum discourse sans majuscules)_
Page compte topoguide : http://www.demov6.camptocamp.org/account (labellisée "Mon compte")

NB : ça doit être facile à coder, car le lien _account_ n'est pas personnalisé.

**Comment by stef74** [comment]
Il faut creer 2 issues en étant simple et concis (pas besoin de jsutifier le pourquoi du comment ... juste ce qu'il faut faire).
Une coté UI pour le lien vers le forum
Une coté forum pour les liens vers le topo

On verra la planification ensuite.

**Comment by jmarcmod** [comment]
Compris, je vais faire ça.

_Edit :_ @stef74 : done.
Forum : [#54](https://github.com/c2corg/v6_forum/issues/54) 
UI : [#973](https://github.com/c2corg/v6_ui/issues/973)
