### ISSUE TITLE
Migration des liens internes au forum postés "à la main"

### ISSUE THREAD

**Issue by jmarcmod** [c2corg/v6_forum#52]
@arnaud-morvan : voici comme convenu des exemples de liens internes "à la main" qui sont cassés sur la beta.
Une redirection sera-t-elle possible ?

Sur la V5, il y a 3 types de liens internes postés à la main :
1) lien vers une autre discussion
2) lien vers un message d'une autre discussion
3) lien vers un message de la même discussion

De plus, ces liens peuvent avoir ou non un titre, soit 6 acs au final.

Voici 3 exemples montrant comment de tels liens ont migré vers la beta V6 ; pour l'exemple 3), j'ai choisi un lien avec titre

1) V5 : le post http://www.camptocamp.org/forums/viewtopic.php?pid=2213482#p2213482
contient un lien cliquable vers la discussion http://www.camptocamp.org/forums/viewtopic.php?id=296126
Ce lien a été automatiquement réduit à l'édition en : `#t296126`
V6 : le post http://forum.demov6.camptocamp.org/t/sorties-trail/171737/11
contient juste la chaîne `#t296126` non cliquable, et inutilisable car ne renvoyant pas à une ID discourse.

2) V5 : le post http://www.camptocamp.org/forums/viewtopic.php?pid=2052476#p2052476
contient un lien cliquable vers le message http://www.camptocamp.org/forums/viewtopic.php?pid=2052393#p2052393 d'une autre discussion.
Ce lien a été automatiquement réduit à l'édition en : `#p2052393`
V6 : le post http://forum.demov6.camptocamp.org/t/ce-que-vous-avez-appris-aujourdhui/138040/436
contient juste la chaîne `#p2052393` non cliquable, et inutilisable car ne renvoyant pas à une ID discourse.

3) V5 : le post http://www.camptocamp.org/forums/viewtopic.php?pid=2165395#p2165395
contient un lien cliquable (avec titre "_démontré dans ce sujet_") vers le message http://www.camptocamp.org/forums/viewtopic.php?pid=2163770#p2163770 de la même discussion.
Ce lien a été automatiquement réduit à l'édition en `[url=#p2163770]démontré dans ce sujet[/url]`
V6 : le post http://forum.demov6.camptocamp.org/t/nanga-parbat-hiver-2016-eli-revol-pour-relever-le-defi-avec-dautres/161239/849 contient cette fois un lien cliquable avec titre, mais le lien dirige vers quelque chose de bizarre (et n'atteint donc pas le bon message) :
http://forum.demov6.camptocamp.org/t/nanga-parbat-hiver-2016-eli-revol-pour-relever-le-defi-avec-dautres/161239/848#p2163770
alors que le bon message devrait être celui-ci :
http://forum.demov6.camptocamp.org/t/nanga-parbat-hiver-2016-eli-revol-pour-relever-le-defi-avec-dautres/161239/764

NB : ces liens internes "à la main", pas très fréquents sur les forums publics, sont très nombreux dans nos forums privés de modération.

**Comment by arnaud-morvan** [comment]
Je peut proposer ceci : 
```
    # rewrite internal links
    s.gsub!(/#t(\d+)/, '[url]/viewtopic.php?id=\1[/url]')
    s.gsub!(/#p(\d+)/, '[url]/viewtopic.php?pid=\1[/url]')
    s.gsub!(/\[url=#t(\d+)\](.*)\[\/url\]/, '[url=/viewtopic.php?id=\1]\2[/url]')
    s.gsub!(/\[url=#p(\d+)\](.*)\[\/url\]/, '[url=/viewtopic.php?pid=\1]\2[/url]')
```
ca remplace par exemple``#t500`` par ``[url]/viewtopic.php?id=500[/url]`` et, par le méchanisme des permaliens, les liens fonctionnerons dans la V6.

**Comment by arnaud-morvan** [comment]
Sauf peut-être pour les liens sur les topics des commentaire du topoguide car le premier post est créé pendant la migration.

**Comment by jmarcmod** [comment]
> Je peut proposer ceci 

Super !

Tant pis pour les commentaires du topoguide, ils ne doivent pas contenir beaucoup de liens forums. Ils contiennent plutôt des liens topoguide (vers une sortie ou un iti), et là les permaliens fonctionneront j'imagine.

**Comment by arnaud-morvan** [comment]
Je parle des liens dans les forums modo (#t99999) qui pointent vers un topic de commentaire qui devraient, en V6, pointer sur le second post car le premier est créé pendant la migration. Ceci dit, j'ai pas eu le temps de tester.

**Comment by jmarcmod** [comment]
> Je parle des liens dans les forums modo (#t99999) qui pointent vers un topic de commentaire qui devraient, en V6, pointer sur le second post car le premier est créé pendant la migration.

OK. Dans ce cas je dirais aussi que ce n'est pas trop grave, car la modération des commentaires, depuis les forums modos forum ou modos topoguide, et qui génère ce type de liens, est en général ponctuelle dans le temps, donc obsolète après quelques semaines.
Au pire ce serait gênant pour des modérations de ces dernières semaines, mais les modos forum retrouveront vite le doc mère d'après le contenu des posts et leur mémoire, et ils pourront corriger les liens à la main sur la V6.
Bref, ne t'embête pas avec ça.

**Comment by jmarcmod** [comment]
@stef74 : cette issue est finalement 6.0 puisqu'elle vient d'être traitée ; on pourra la tester sur la version définitive dans 1 semaine.

**Comment by fbunoz** [comment]
> par le méchanisme des permaliens, les liens fonctionnerons dans la V6.

Ok, si ça fonctionne (ça veut dire plusieurs dizaines ou centaines de milliers de permaliens...).
Lors de la migration, les citations sont correctement migrées.
Sur la V5, une citation comporte un lien vers le post d'origine.
Sur la V6, il y a toujours ce lien, et il est migré correctement, alors que tous les Id des posts et des topics ont changé (c'est une vraie migration en changeant l'ID dans la balise de citation, ça n'utilise pas les permaliens). Sera-t-il possible de faire pareil pour les liens ?
Ca sous entend que la correspondance entre les ID V5 et ID V6 a été sauvegardé dans une base.
Pour éviter tout ça, il aurait été plus simple de ne pas modifier les ID à la migration, mais bon.

**Comment by jmarcmod** [comment]
**Migration du 28/11**
Ils ont bien été modifiés, reste à voir si les permaliens permettront d'activer ces liens.
Voici ce que sont devenus mes 3 exemples (le 3ème avec titre) :
http://datamigration.exoscale.infra.camptocamp.org/t/sorties-trail/170311/9
`[url]/viewtopic.php?id=296126[/url]`
http://datamigration.exoscale.infra.camptocamp.org/t/ce-que-vous-avez-appris-aujourdhui/138033/436
`[url]/viewtopic.php?pid=2052393[/url]`
http://datamigration.exoscale.infra.camptocamp.org/t/ce-que-vous-avez-appris-aujourdhui/138033/436
`[url=[url]/viewtopic.php?pid=2163770[/url]]démontré dans ce sujet[/url]`

**Comment by jmarcmod** [comment]
> par le méchanisme des permaliens, les liens fonctionnerons dans la V6.

@arnaud-morvan : 
Quand est-il prévu de faire tourner le script qui transformera les liens V5 en liens V6 grâce aux permaliens ?

@stef74 : cette issue n'est pas go live, c'est au moins 6.1.

**Comment by arnaud-morvan** [comment]
Ceci est déjà plus ou moins dans la boite, reste à bien tester avant de l'exécuter. Pas sur de trouver le temps cette semaine.

**Comment by fbunoz** [comment]
> Ceci est déjà plus ou moins dans la boite, reste à bien tester avant de l'exécuter. 

Vous avez fait du bon boulot, visible sur la démo !
Mais il y a des problème avec les lien vêtis (lien sur du texte) : 
https://forum.demov6.camptocamp.org/t/amelioration-du-topoguide/69118/52 (lien en bas du post).
On a des trucs du style : [url=[url]/viewtopic.php?id=136706[/url]+]recueil des problèmes d'affichage du site[/url]
En corrigeant en [url=/viewtopic.php?id=136706]recueil des problèmes d'affichage du site[/url] ça fonctionne. Bien pensé à supprimer le +.

**Comment by arnaud-morvan** [comment]
Nous avons corrigé la plupart des liens internes au forum.
Les liens avec des "+" n'ont pas été pris en compte.

**Comment by jmarcmod** [comment]
> Nous avons corrigé la plupart des liens internes au forum.

Sur la version de prod ? j'ai fait peu de tests (pas le temps), mais sur une dizaine de cas, les liens étaient toujours cassés (avec ou sans "vêti")

> Les liens avec des "+" n'ont pas été pris en compte.

Dommage, mais ceci dit ça concerne surtout les forums privés modos/assoce, donc moins grave.

**Comment by arnaud-morvan** [comment]
J'ai testé les lien donnés dans la description du ticket, ils fonctionnent tous.

**Comment by jmarcmod** [comment]
Après de nouveaux tests, effectivement, la plupart des liens sont corrigés en prod.
Pour le reste, on corrigera à la main.
Bravo !
J'ai fermé l'issue.
