### ISSUE TITLE
"comments" tous datés du 26/11/16

### ISSUE THREAD

**Issue by jmarcmod** [c2corg/v6_forum#55]
**Migration du 28/11**
La page "latest" (toutes catégories confondues) est squattée par les "comments" qui sont tous datés du 26 novembre.
Pour les autres catégories, tout semble normal (date V5).
Est-ce dû au statut particulier de ces discussions ?
Peut-être supprimer les comments puis refaire un import correct de ces comments ?

**Comment by arnaud-morvan** [comment]
Pour les commentaires nous créons le premier post (avec le lien vers le document topoguide) lors de la migration.
Je vais faire une requête SQL pour mettre la date du premier post V5 (second post V6) dans le premier post V6.

**Comment by jmarcmod** [comment]
@arnaud-morvan 
Sur la version de prod du jour, les derniers commentaires (post 21/11) sont encore tous datés d'il y a 2 jours, et ce depuis 2 jours.
Peut-être faut-il refaire la requête SQL ?

**Comment by jmarcmod** [comment]
Par ailleurs je vois 2 commentaires qui viennent d'être créés (15h15), et qui ne sont attachés à aucune catégorie, à savoir 660519_fr et 471244_fr.

_Edit :_ ce petit soucis semble quant à lui résolu.

**Comment by jmarcmod** [comment]
> Sur la version de prod du jour, les derniers commentaires (post 21/11) sont encore tous datés d'il y a 2 jours, et ce depuis 2 jours.

Ça n'a pas été corrigé, mais ça ne concerne qu'environ 60 commentaires (entre le 21/11 et le 5/12), qui ont donc un retard de datation d'au plus 2 semaines... ils sont maintenant descendus loin dans la chronologie, donc ne squattent plus les listes "récents" ; et surtout, la datation est correcte dans le fil de commentaires du document.

Je ferme donc cette issue.
