### ISSUE TITLE
discourse menu

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_forum#56]
- [x] With Safari in mobile, hamburger and order with logo is different betwen forum and topoguide 
![capture d ecran 2016-11-29 a 19 29 28](https://cloud.githubusercontent.com/assets/3962997/20723284/38b5c8ea-b66a-11e6-9a4e-93a4568f4bbd.png)
- [ ] incorrect position of the "close menu" button with FF in mobile screens

**Comment by asaunier** [comment]
* [x] the menu icons are no longer visible (tested with Chrome and FF) (it was OK earlier when we discussed the menu PR - don't know what happened in the meantime?)

<img width="322" alt="capture d ecran 2016-11-29 a 23 08 20" src="https://cloud.githubusercontent.com/assets/1192331/20731066/ed85f8a8-b688-11e6-8b80-acf38c594a15.png">

**Comment by ginold** [comment]
- already ok for icons (2 styles were active in the same time, probably one overwrote the other somewhere)
- when the demo will be updated, the UI and forum menus will have both the same order on mobile (logo - hamburger). The new version is only visible on the forum for now. I can update the style later.

**Comment by ginold** [comment]
The style of the button on mobile is not the same, because it plays well with the other buttons on discourse, on the right. But up to you if you want it to be exactly as on the UI.

**Comment by jmarcmod** [comment]
> the menu icons are no longer visible

Idem chez moi (FF) malgré un grand écran (1920).

**Comment by ginold** [comment]
C'est la 3ème fois que je réactive les styles, je ne comprends pas... reéssayez maintenant.

**Comment by asaunier** [comment]
OK for me now.

**Comment by jmarcmod** [comment]
OK pour moi aussi désormais.
L’icône du bouton "forum" est désormais une bulle et non un hamburger, mais j'imagine que c'est voulu.

**Comment by ginold** [comment]
Effectivement, je trouve qu'une bulle-commentaire est plus appropriée au `Forum` qu'à l'`Association` (sera pareil sur la démo après la mise-à-jour).

**Comment by ginold** [comment]
- [x] UI and Forum: if on tablet, when you hover with mouse on the icons, the tooltip is cut.

**Comment by fbunoz** [comment]
Le design du forum que j'ai ajouté cache le menu hamburger quand on est en mobile en portrait. Mais si je le désactive, c'est bon.
Je corrigerai ce problème, mais je n'ai pas encore trouvé la cause.

**Comment by jmarcmod** [comment]
> OK pour moi aussi désormais.

Mais ce soir les icônes sont de nouveau partis.

**Comment by asaunier** [comment]
En effet.

@fbunoz est-ce que tu n'aurais pas remis tes adaptations de styles ? Peut-être que certaines entrent en conflit avec le menu et font disparaître les icones ?

**Comment by fbunoz** [comment]
En effet je l'ai remis. C'est facile à voir : si la barre du haut à une bordure orange, c'est que le design du forum est activé.

Bon ben ya plus d'impact que je pensais (c'est quand même bizarre).

**Comment by fbunoz** [comment]
> Bon ben ya plus d'impact que je pensais (c'est quand même bizarre).

C'est corrigé.
Ce n'était pas du tout les règles que j'ai ajouté qui étaient en cause.
Mais juste en changeant l'ordre des CSS (CSS du forum après le CSS du menu), ça fonctionne, sans toucher à aucune règle !
C'est peut être du à l'import du CSS de bootstrap ?
En tout cas ça marche. 2-3 petites corrections à faire pour le menu sur mobile (marges à corriger), et ce sera bon.

**Comment by jmarcmod** [comment]
OK maintenant :)

@stef74 : à fermer ?
