### ISSUE TITLE
Automatic email and url domain config

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_forum#58]
Some users (all users ?) have received a mail with a summary of last forum activity.
This feature has been turned off in admin config, but maybe these email were sent before an admin changes the config (juste after an update which reset the config, etc), and were in standby in a server before the server has been configured correctly ?
The problem is that this mail contains link to http://forum.camptocamp.org domain.
It implies that the mail generator use a config with this domain. In admin interface, there is no config like that in demo or data-migration instances. It is strange.
Another problem is the domain must be https instead of http.
I don't know where to config this url domain.

**Comment by arnaud-morvan** [comment]
When we bootstrap the discourse app, there is a settings DISCOURSE_HOSTNAME that I've set to ``forum.camptocamp.org``, but I do not find setting for the scheme (HTTP / HTTPS).

**Comment by arnaud-morvan** [comment]
Maybe we should check ``force https`` in settings / security

**Comment by jmarcmod** [comment]
Cette issue est-elle encore d'actualité ?
Plus personne n'a reçu de résumé d'activité du forum depuis le 6 décembre (donc avant mise en prod).
