### ISSUE TITLE
Discourse menu config for prod

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_forum#59]
Make sure that the HTML code used for the sidemenu uses the actual prod base URL, not the demo one:
https://github.com/c2corg/v6_ui/blob/master/less-discourse/menu.html#L2

**Comment by asaunier** [comment]
> Make sure that the HTML code used for the sidemenu uses the actual prod base URL,

Fixed by @arnaud-morvan 

But there is also this change to do: https://github.com/c2corg/v6_ui/pull/1122/files

**Comment by asaunier** [comment]
> But there is also this change to do: https://github.com/c2corg/v6_ui/pull/1122/files

Fixed also by @arnaud-morvan

**Comment by fbunoz** [comment]
Sorry, I can't access to the prod until tonight (I can't modify the hosts config here).
