### ISSUE TITLE
Anonymous posting

### ISSUE THREAD

**Issue by gberaudo** [c2corg/v6_forum#6]
There seems to be no way to post in Discourse without having an account.
However, when logged in, it is possible to switch to an `anonymous` mode.

See https://meta.discourse.org/t/how-will-anonymous-posting-mode-work/25370

**Comment by asaunier** [comment]
Thanks, I have notified the clients of this issue (?). Will let them investigate if needed.

Does this mean that all migrated message not related to an account in v5 will be bound to that System user?

**Comment by gberaudo** [comment]
Yes, it seems so.

**Comment by asaunier** [comment]
The client is not very found of the "anoymous posting" feature and will probably disable it.
Anyway it seems we don't have to do anything about this issue. Closing then.
