### ISSUE TITLE
Broken notification link

### ISSUE THREAD

**Issue by tonio** [c2corg/v6_forum#61]
Connected on the forum, I got a notification 
«Vous avez gagné Basic User», linked to https://forum.camptocamp.org/badges/1/basic?username=toni0

Looks like a broken link:

![screenshot from 2016-12-08 11-20-04](https://cloud.githubusercontent.com/assets/21686/21006243/52d90f1e-bd38-11e6-832b-6db0022c7ac5.png)

**Comment by stef74** [comment]
On which page do you connect ?

**Comment by tonio** [comment]
https://www.camptocamp.org/auth-sso

**Comment by asaunier** [comment]
@stef74 Go to the forum > click on your user account in the top right corner > click on "Vous avez gagné Basic User" > you get such a page.

Perhaps a Discourse setting error? Are those badges actually available?
@fbunoz what do you think?

**Comment by fbunoz** [comment]
It's normal.
The badge was not active.
But they were active during migration,  then all users with posts have
received some badge...

**Comment by jmarcmod** [comment]
Ce sont les badges que chacun a reçu à l'ouverture de la V6.
Bubu a désactivé les badges, on est tranquille maintenant (c'est juste pas rétroactif).
Les notifications dédiées disparaitront dans la chronologie.

@stef74 : issue à fermer.
