### ISSUE TITLE
mail answering

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_forum#62]
I try to answer by email 

but 

Delivery to the following recipient failed permanently:

     replies+c828bfc6c0227f1daf11fbcd7da20f4f@camptocamp.org

Technical details of permanent failure:
Google tried to deliver your message, but it was rejected by the server for the recipient domain camptocamp.org by aspmx.l.google.com. [2a00:1450:400c:c09::1b].

The error that the other server returned was:
550-5.1.1 The email account that you tried to reach does not exist. Please try
550-5.1.1 double-checking the recipient's email address for typos or
550-5.1.1 unnecessary spaces. Learn more at
550 5.1.1  https://support.google.com/mail/?p=NoSuchUser q126si14788903wme.18 - gsmtp

----- Original message -----

DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20120113;
        h=mime-version:in-reply-to:references:from:date:message-id:subject:to;
        bh=vkYMvpyCEGmnou6ZTbv57iwGCzvibKP4h4d7cOQrrfQ=;
        b=v9kOczXbZ6qtud2g16sB3xRBWP+CTE9vKKigs4gKwJhg+bfYeNQRnIN1AOr9UJgPo2
         AHjA2QN2yFk9greqCEtLLUr6UWWYt+/wuJcXbwxjmocy2lRiZ+cY7dGQbGcE+T0fFOKT
         QvV5MbudufZVxoHxe3m/7HBKSmEJRMtlJQz75RnTBaE3ur46o2SeJCqrDyNplG1huleA
         8eUk6s/M3Trnq64UDjAqsE6MEPJe4SOJf6xQGtpapYEW8uCxVWR7vbRndDS5j5QlnTDk
         Z6W9tcRBqfDRcfoMBDvxFedOgfn4TL1ZWH67ST7b8/uAI2IPPiikjxEAezLkrcOvKFKE
         6mMA==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20130820;
        h=x-gm-message-state:mime-version:in-reply-to:references:from:date
         :message-id:subject:to;
        bh=vkYMvpyCEGmnou6ZTbv57iwGCzvibKP4h4d7cOQrrfQ=;
        b=iiymXmHgCyzcbporWnA/VukRwyW7Dyc/71CG34yKtckSdG6TRkVcALTSm4rny6hBQJ
         u789V8yrjVdf0C1uKdx+1w4Fuymv4ILe/f5ORyRYCIXznzG7C5dTfPQBZJ4SZeA0puZh
         bCRxKBGsHSvTcPdTJO3l3QfDuYsT24B7AuRkfIqRvkCO5buuB0J08jc/dTg0DbgTDpVz
         /iDWYNLw+J4ll0oPdER4YwqNlkqpMeRNth+V7jrE/ZBrgVshlrNEdrB78H6LzMsCx/st
         mKvsrAy38YsowJCDzEDYYZ5kGedX/wCt+LxMlZMdcWL6hqhBaWfZQJF/ATXGkEFmbbDy
         k6mw==
X-Gm-Message-State: AKaTC036gjp0zWqGi5bq9oh7qdTkKblmVtIJKiMq87pOwc5oDm1NYms0FyhxZJbbJRZy1iu+RgfnAJnicgbagw==
X-Received: by 10.194.157.165 with SMTP id wn5mr7248317wjb.8.1481230139464;
 Thu, 08 Dec 2016 12:48:59 -0800 (PST)
MIME-Version: 1.0
Received: by 10.80.182.123 with HTTP; Thu, 8 Dec 2016 12:48:18 -0800 (PST)
In-Reply-To: <topic/173336/1888702@forum.camptocamp.org>
References: <topic/173336@forum.camptocamp.org> <topic/173336/1888702@forum.camptocamp.org>
From: Stephane Peiti <stephane.peiti@gmail.com>
Date: Thu, 8 Dec 2016 21:48:18 +0100
Message-ID: <CADuT6UzsASPX2OKks0h5jZwQADD9qDXAtg3onfu31NEMK-Y=OA@mail.gmail.com>
Subject: Re: [Forum - Camptocamp.org] [C2C V6/V6 - Vie et organisation du
 projet] Prochaines versions V6.X
To: "Forum - Camptocamp.org" <replies+c828bfc6c0227f1daf11fbcd7da20f4f@camptocamp.org>
Content-Type: multipart/alternative; boundary=089e013c656a4b277905432bc42e

**Comment by arnaud-morvan** [comment]
There is some settings to fill in discourse for pop3 polling: 
https://forum.camptocamp.org/admin/site_settings/category/email

And not all are filled (username, password).
But something should be also configured on camptocamp.org email server.

**Comment by mfournier** [comment]
I'll take care of this, we've discussed this today with @fbunoz.

**Comment by jmarcmod** [comment]
Je confirme : impossibilité de répondre par mail lorsqu'on reçoit une notification par mail, que ce soit pour un MP ou pour un post du forum.

**Comment by stef74** [comment]
@mfournier have you discuss with @fbunoz ?

**Comment by mfournier** [comment]
I set this up just now. I wasn't able to test much by myself, but observation seems to show it works well.

@fbunoz FYI I finally settled for `replies@camptocamp.org` as many emails were already sent by discourse with this address in the reply-to field.
