### ISSUE TITLE
Discourse config update has no effect

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_forum#67]
Normaly, a change in the Discourse config (design, translation, ...) has an effect immediately.
But since 9 dec PM, after ~1-2h, the config is reverted to the config of 9 dec AM.
it seems that some generated files in a cache are regulary updated with an old version.
For example, the custom CSS : https://forum.camptocamp.org/site_customizations/7e202ef2-56d7-47d5-98d8-a9c8d15e57dd.css?target=desktop&v=e9d52a41435c3f161efbe4c77e3b5429&__ws=forum.camptocamp.org

But the simple config is also impacted, as the mail title send by Discourse : the prefix is [Forum Camptocamp.org] whereas I changed it to [c2c].

**Comment by asaunier** [comment]
Wouldn't it be a problem with the Discourse Docker container that would be reset to a given state again and again?

**Comment by mfournier** [comment]
On Sun, Dec 11, 2016 at 11:55:50PM -0800, Alex Saunier wrote:
> Wouldn't it be a problem with the Discourse Docker container that would
> be reset to a given state again and again?

No, discourse's container itself holds no state, everything which needs to
be persisted is stored in external volumes (ie: a directory outside of
docker's scope) or in a database (postgresql & redis).

Further than that, the discourse container itself hasn't been restarted
since 2016-12-07T22:49:19.533+01:00.

**Comment by fbunoz** [comment]
Maybe, I don't know how it works.
To know if the last version is used, check this page : https://forum.camptocamp.org/latest
There should be a column with avatars.

**Comment by fbunoz** [comment]
The bug always exist.
Then, the change on the menu (add "outing" item") is not visible on forum (whereas the change has been done in the admin interface).

**Comment by jmarcmod** [comment]
Si j'ai bien compris, aucune modif de design ne peut plus être enregistrée depuis le 9 décembre.
Ca concerne entre autres les tags, le menu "sorties" à gauche, l'avatar du dernier posteur dans les listes de discussions, le nettoyage des "récents" et "non lus", les boutons ou boîtes qui s'ouvrent en partie hors de l'écran à droite etc.

**Comment by arnaud-morvan** [comment]
Concerning the html/css customisations
I've removed some trailing white spaces and saved changes. "Outings" link now appears on the left menu.

**Comment by arnaud-morvan** [comment]
Concerning the email subject
* I've added a trailing whitespace, saved and sent a test email to myself, but the email subject is still contains the site title (not [c2c]).
* I've put the string "c2c" in setting "email prefix (Le [label] qui sera utilisé dans le sujet des courriels. Par défaut il prend la valeur de 'title'.), saved and sent a test email to my self. Now the email subject is: "[c2c] Test de délivrabilité d'un courriel".

@fbunoz : does the setting "email prefix" fully match with your requirements ?

**Comment by arnaud-morvan** [comment]
Now we should regularly look at the left menu to see if the Outings entry disapear, and when ? Is this can be matched with some background job.

**Comment by jmarcmod** [comment]
> Now we should regularly look at the left menu to see if the Outings entry disapear, and when ?

Pour l'instant ça tient.
Je vais essayer de surveiller.

**Comment by fbunoz** [comment]
> Now we should regularly look at the left menu to see if the Outings entry disapear, and when ?

Now, if we reload a forum page, the outing menu entry is not visible anymore, neither the design changes (your HTML change had also set the new design (one column with avatars in topics list)).

**Comment by jmarcmod** [comment]
Je confirme, ça a sauté.

**Comment by arnaud-morvan** [comment]
Nous avons redémarré le conteneur discourse, le menu semble stable cette fois. A suivre ...

**Comment by fbunoz** [comment]
En effet, ça n'a toujours pas sauté !

**Comment by jmarcmod** [comment]
Et ça tient toujours !

**Comment by desnoes** [comment]
@fbunoz and @jmarcmod: can we close the issue ?

**Comment by jmarcmod** [comment]
J'attendrais encore demain soir, pour être sûr que ça ne va pas sauter à nouveau.

**Comment by desnoes** [comment]
@jmarcmod @fbunoz : la config tient toujours ? Si oui, je ferme l'issue

**Comment by jmarcmod** [comment]
Oui, elle tient !
Tu peux fermer.
