### ISSUE TITLE
Transfert de connexion topoguide -> forum

### ISSUE THREAD

**Issue by jmarcmod** [c2corg/v6_forum#70]
**Bug à traiter en priorité !**

Depuis 2 jours (16 décembre), un bug de connexion touche de nombreux contributeurs, de manière assez aléatoire : connexion OK sur le topoguide, mais pas de connexion sur le forum ; et une tentative de connexion depuis le forum aboutit à :
> _Il y a un problème avec votre compte. Merci de contacter l'administrateur du site._

Divers navigateurs concernés (dont Firefox) ; supprimer cookies et vider cache, ou recharger simplement la page, semblent inopérant.
Ça se répare tout seul mais au bout d'un temps plus ou moins long... bug et réparation semblent très aléatoires.

On a cru un moment que c'était lié à un changement de langue, mais non.

En revanche ça semble ne se produire que si l'on est préalablement déconnecté ; en attendant, il est donc conseillé de rester connecté en permanence.

Par ailleurs ça semble lié au compte : en changeant de compte, il arrive qu'on puisse se connecter normalement ; mais parfois aucun compte ne marche.

**Comment by arnaud-morvan** [comment]
Quelqu'un avait semble-t'il bloqué l'url de l'un des serveur HAProxy, dans Forum / Admin / Journaux / IP surveillées.
Conséquence il était devenu impossible de se logger à travers ce proxy (ceci ne semble avoir aucune incidence sur la lecture des post, le blocage se fait sur l'authentification de l'utilisateur).

@mfournier : As-tu des infos sur le transfert de l'IP du client au travers du HAProxy.

**Comment by mfournier** [comment]
On Tue, Dec 20, 2016 at 07:27:36AM -0800, Arnaud Morvan wrote:
> Quelqu'un avait semble-t'il bloqué l'url de l'un des serveur HAProxy, dans Forum / Admin / Journaux / IP surveillées.
> Conséquence il était devenu impossible de se logger à travers ce proxy (ceci ne semble avoir aucune incidence sur la lecture des post, le blocage se fait sur l'authentification de l'utilisateur).

Arf... Merci pour le debuggage !

> @mfournier : As-tu des infos sur le transfert de l'IP du client au travers du HAProxy.

Oui, c'est le sujet de #66.

**Comment by mfournier** [comment]
@jmarcmod on te laisse passer l'info auprès de l'équipe des modérateurs ? Tant que #66 n'est pas résolu, ne pas se baser sur les adresses IP. Sinon ça casse l'authentification.

**Comment by jmarcmod** [comment]
Bravo pour le débogage !
@arnaud-morvan et @mfournier : personne à ma connaissance n'a suivi les IP récemment, on sait depuis plus d'une semaine que ce sont celles du serveur et donc que ça ne sert à rien.
Je me demande plutôt si le pb ne vient pas d'un modo qui a supprimé il y a 5 jours un utilisateur spammeur (ce qu'il ne faut absolument pas faire, mais il ne devait pas le savoir), or la suppression semble liée à l'IP ;
cf le journal admin (action des modérateurs) : 
> Supprimer l'utilisateur
5 j
Courriel: fifadelia@outlook.com
IP: 159.100.252.5
Afficher
Supprimé depuis la liste des messages en attente de validation

En tout état de cause je vais écrire à tous les modos ne pas surveiller les IP (pour l'instant), et de ne jamais supprimer d'utilisateur.

J'ai aussi créé une issue pour désactiver la suppression d'utilisateurs : [#85](https://github.com/c2corg/v6_forum/issues/85)

**Comment by jmarcmod** [comment]
>Je me demande plutôt si le pb ne vient pas d'un modo qui a supprimé il y a 5 jours un utilisateur spammeur (ce qu'il ne faut absolument pas faire, mais il ne devait pas le savoir)

Après enquête, discourse a bloqué un 1er post, pour suspicion de spam, demandant d'accepter ou de refuser le message ; le modo a refusé... sans se douter que discourse supprimerait alors de facto l'utilisateur !
Super dangereux cette fonctionnalité...
