### ISSUE TITLE
Forum migrating : bad use of V5 pseudo

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_forum#8]
In discourse, the pseudo is the login, and is limited to 20 alphanum characters (without space, accents, ...).
But in V5, the pseudo is not the login, and can be longer than 20 char, with space en accents.

Then, in the test forum, in a post the poster name is the V5 login instead of V5 pseudo.

The solution is to change the field showed as poster name (anywhere it is visible in discourse) : use the complete name instead of login/pseudo.
The migrating must set the complete name with the V5 forum pseudo.
The V5 topoguide name is lost (or a field is added).

**Comment by gberaudo** [comment]
Hi @fbunoz. Here is how it was implemented:
https://github.com/c2corg/discourse/blob/70d193523f4745de394ffce58884c6278a7b7398/script/import_scripts/punbb.rb#L67-L68

Do you suggest it should be changed to use the `topo_name` column instead of `username`?

**Comment by gberaudo** [comment]
Handled in branch https://github.com/c2corg/discourse/tree/import_punbb.

**Comment by fbunoz** [comment]
If I understand correctly, in the V6 (topoguide), there are the login (non editable) and the full name (editable).
For the migrating, the Discourse nicknames are derived from V5 login, or V5 forum_name, or V5 topo_name (we must decide which name will be used).
An user can't change the Discourse nicknames using discourse profile (the fields are not editable).
But I don't understand if the Discourse full name will be updated when an user changes the V6 full name.
And the Discourse username will be fixed for ever ?

**Comment by gberaudo** [comment]
I checked the Discourse SSO guide and it seems it is OK to change the username and full name afterwards.

**Comment by gberaudo** [comment]
However, it will probably not rewrite the `@user` links in the messages.

**Comment by gberaudo** [comment]
I tried to change my pseudo on the assoce instance (no sso, just plain Discourse).
It was not possible as a normal user. As a admin I get the following message:

```
Si vous modifiez votre pseudo, toutes les citations de vos messages et les mentions @pseudo seront cassées. Êtes-vous absolument sûr de vouloir le faire ?
```

I guess the problem will also occur with SSO.

**Comment by fbunoz** [comment]
I think it's not a problem if the @pseudo are broken : 
- The link to the profile which is on "@pseudo" is lost : not a problem.
- The subscription to a topic where the old pseudo is quoted, is keeped.
- I don't understand what "toutes les citations de vos messages seront cassées" means. I see no difference in quote functionnalities if I change the pseudo in the quote tag.

**Comment by fbunoz** [comment]
Then, if is possible to change the Discourse username and full name via V6 UI (using Discourse SSO), it means that the V5 login, V5 forum_name and V5 topo_name can be migrated : 
- V5 login => V6 login
- V5 forum_name => Discourse username (after changes by migrating script to remove accents and to uniquify the usernames)
- V5 topo_name => V6 full name and Discourse full name

Is it possible ?

**Comment by gberaudo** [comment]
Seems doable to me. We would need some UI for changing pseudo; @asaunier, any opinion?

**Comment by gberaudo** [comment]
@fbunoz, could you confirm the v5 forum_name is the `username` column of the punbb_user table?
Also see https://github.com/c2corg/v6_forum/issues/22

**Comment by fbunoz** [comment]
@gberaudo : yes, the V5 forum name is the punbb_users.username field.

**Comment by gberaudo** [comment]
Thanks for the confirmation @fbunoz.

**Comment by fbunoz** [comment]
On the beta import visible on http://forum.demov6.camptocamp.org/users?order=post_count&period=all, the forum name is not correct for some users.
For example, my forum name has been migrated to fbunoz, instead of Bubu (which respects the Discourse username rules from 1999 :-) ).

**Comment by asaunier** [comment]
"fbunoz" is your login, right?
A mix between the login and the forum name?

**Comment by fbunoz** [comment]
Yes, is my login.

**Comment by jmarcmod** [comment]
Idem pour moi.
Sur V5, login : jmc / pseudo forum et topoguide : J.Marc (compatible avec les règles Discourse)
Sur V6 Discourse, login : jmc / pseudo forum : jmc2 / pseudo topoguide (= "nom complet") : jmc
Et je ne peux pas modifier ce pseudo forum sur Discourse.

Même constat chez d'autres testeurs (dont Hervé S.)

**C'est sans doute le plus grave de nos problèmes, car totalement bloquant :** comme dit à l'époque, beaucoup de forumers prennent comme login leur nom, nom qu'ils veulent garder secret ; on ne peut pas dévoiler ainsi au public l'identité de plein de contributeurs. Surtout que ce login n'est pas modifiable.

**Comment by jmarcmod** [comment]
Problème bloquant, détaillé dans l'issue [#48](url=https://github.com/c2corg/v6_forum/issues/48).

**Comment by stef74** [comment]
Voir #48
