### ISSUE TITLE
Forum migrating : bad post ID and quote infos improvement

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_forum#9]
**Bad post ID**
The forum migrating has not keep the V5 post ID but has renumbered the ID. Then, a link to a specific post will be broken (any link : in a post, in the quote header, in the topoguide, on an external site, etc).

**Quote improvment**
More over, the quote tag migrating has not kept the post ID.
The post ID is not managed yet in discourse, but it will have to be.
A post has already a html attribut "data-post-id" filled with the post ID.
To prepare the futur post ID managment, a quote migrating must be like this :

`[quote=mollotof|2087176]`
=>
`[quote="mollotof, id: 2087176, post:23, topic:11892"]`

The V5 forum allow single or double quotes in the pseudo. In the migrating, we can remove double quote to avoid some problems.

**Comment by gberaudo** [comment]
This would be complex.

**Different post IDs**
This may be tricky as there exists some invalid posts that are skipped
during import and that would shift subsequent ids.

**Quote improvment**
This would require extracting quotes from message bodies and:
- find associated v5 topic and then discourse topic;
- find the position of the post in the topic;
- replace v5-style quote by new discourse-style quote.

**Comment by gberaudo** [comment]
`Quote improvement` handled in branch https://github.com/c2corg/discourse/tree/import_punbb.
`Different post IDs` should be handled globally in #15.

**Comment by fbunoz** [comment]
Why is it not pssible to simply use the punbb id as discourse id instead
using a counter ?
Missing id is not a problem in discourse BD, because we can remove posts
and topics in discourse, and their id will miss without breaking anything.

**Comment by gberaudo** [comment]
It would require messing with the migration base classes provided by Discourse.
