### ISSUE TITLE
Conflicts between users

### ISSUE THREAD

**Issue by arnaud-morvan** [c2corg/v6_forum#90]
Le compte Sam_le_Pirate (topo : Jean Luc Laborie / email : jean-luc-laborie@orange.fr) est bugué : profil public inaccessible, on n'a que le profil admin :
https://forum.camptocamp.org/admin/users/10095/sam_le_pirate
Profil topo : https://www.camptocamp.org/profiles/10196/fr

A côté, il y a le compte vide samlepirate (topo : samlepirate / email : samuel.breton@orange.fr)
https://forum.camptocamp.org/admin/users/31070/samlepirate
créé semble-t-il lors de la migration du 22 novembre.
Profil topo : https://www.camptocamp.org/profiles/342547/fr
Or ce compte a un profil public valide, qui renvoie à... Sam_le_Pirate !
https://forum.camptocamp.org/users/sam_le_pirate/activity

Je me demande s'il n'y a pas eu télescopage des 2 scripts de modif du pseudo : l'ancien scrip tuait les espaces, le nouveau les remplace par un undescore... d'où 2 comptes (pseudo forum sur V5 : sam le pirate).
Bref, certains comptes ont été dupliqués, le 1er est actif mais bugue, le second empêche le changement de pseudo...

Catherine avait déjà noté ce bug : compte avec doublon n'appartenant à personne, et profil public non cliquable ; mais je n'avais pas trop compris à l'époque.

J'attends vos retours, puis je créerai une issue.

J.Marc

**Comment by arnaud-morvan** [comment]
Effectivement, nous avons écrasé les "username" dans le forum, mais cela n'était pas suffisant.
Il faut aussi mettre à jour les tables "annexes" aux utilisateurs.
Il faut donc utiliser l'ORM de discourse pour ré-écraser le username, en passant par un username intermédiaire, pour s'assurer que la modification soit répercutée.

**Comment by arnaud-morvan** [comment]
J'ai créé un script pour synchroniser par SSO tous les utilisateurs : 
https://github.com/c2corg/v6_api/compare/master...amorvan_sync_usernames

Sur la démo, il semble qu'il faille prévoir 4h de traitement.

**Comment by arnaud-morvan** [comment]
@fbunoz @jmarcmod

J'ai tenté d'exécuter mon script sur la base de démo, mais j'ai rencontré un nouveau problème.

A savoir, lors du premier login, discourse cherche l'utilisateur par son email, puis stocke en base l'identifiant topoguide de l'utilisateur.
 
Certains utilisateurs ont changé leur email entre la migration du forum et du topoguide.
Lorsque ces utilisateurs se sont identifiés la première fois sur la V6, ceci donc a créé un nouvel utilisateur.

Après quelques recherches : https://meta.discourse.org/t/ability-to-merge-users/9220 
Il n'existe pas vraiment de méthode prête à l'emploi pour merger deux utilisateurs.
De mon point de vue, la meilleure méthode serait : 
* de basculer manuellement la propriété des posts du nouvel utilisateur sur l'ancien.
  * => Les notifications ne suivront pas.
* de supprimer le nouvel utilisateur.
* d'écraser l'adresse mail des utilisateurs avec celle du topoguide (sur la base du import_id) :

```
UPDATE users
SET email = c2corg_users.email
FROM
    user_custom_fields,
    dblink('dbname=c2corg', '
        SELECT
            id,
            email
        FROM users.user
    ') AS c2corg_users (
        id integer,
        email text)
WHERE user_custom_fields.value::integer = c2corg_users.id AND user_custom_fields.name = 'import_id'
AND users.id = user_custom_fields.user_id
AND c2corg_users.email != users.email;
```

* de lancer un sync_sso sur tous les utilisateurs (pour remplir le champ external_id) avec le script proposé ci-dessus.

Je vais faire quelques essai sur la base de démo.

**Comment by arnaud-morvan** [comment]
Voici une aperçu qui nous retourne 10 lignes .
3 comptes seulement sont dupliqués.
```
SELECT
    c2corg_users.id,
    c2corg_users.forum_username,
    c2corg_users.email,
    old_users.id old_id,
    old_users.username old_username,
    old_users.email old_email,
    new_users.id new_id,
    new_users.username new_username,
    new_users.email new_email
FROM
    dblink('dbname=c2corg', '
SELECT
    id,
    forum_username,
    email
FROM users.user
') AS c2corg_users (
  id integer,
  forum_username text,
  email text)
LEFT JOIN user_custom_fields ON user_custom_fields.value::integer = c2corg_users.id AND user_custom_fields.name = 'import_id'
LEFT JOIN users old_users ON old_users.id = user_custom_fields.user_id
LEFT JOIN users new_users ON new_users.email = c2corg_users.email
WHERE c2corg_users.email != old_users.email;
```

   id   |   forum_username    |             email              | old_id |    old_username     |              old_email              | new_id | new_username |          new_email           
--------+---------------------+--------------------------------+--------+---------------------+-------------------------------------+--------+--------------+------------------------------
   7204 | pvantiel            | pvtiel@gmail.com               |   7133 | pvantiel            | pietervt@bluewin.ch                 |  42003 | pvantiel1    | pvtiel@gmail.com
   7794 | Bruno_Chretien      | bruno.chretien@safrangroup.com |   7717 | Bruno_Chretien      | bruno.chretien@snecma.fr            |        |              | 
 124885 | jetable             | 3vj57qe0vz02rfl@jetable.net   +|  16072 | jetable             | 3vj57qe0vz02rfl@jetable.net         |        |              | 
        |                     |                                |        |                     |                                     |        |              | 
 148711 | JD148711            | jd.schoop@gmail.com            |  18436 | JD148711            | riderclimber@hotmail.com            |        |              | 
 204639 | alex_buisse         | public@alexbuisse.com          |  22547 | alex_buisse_2       | climb@alexbuisse.com                |  50222 | alex_buisse  | public@alexbuisse.com
 225172 | maxime_tavan        | maxime_tavan@hotmail.com       |  23762 | maxime_tavan        | pourkoimoi_pourkoipalui@hotmail.com |        |              | 
              | thibaut.fr@voila.fr                 |  50137 | tsan1        | thibaut.com@yahoo.com
 357589 | rabbits             | florian.daubarede@outlook.fr   |  31965 | rabbits             | florian@daubarede.org               |  50142 | rabbits1     | florian.daubarede@outlook.fr
 578404 | kalibre             | kmeuzard@gmail.com             |  41487 | kalibre             | hellokalibong@gmail.com             |        |              | 
 760652 | Jean-Baptiste_Renie | jb.renie@fidemis.com           |  47565 | Jean-Baptiste_Renie | jb@boxtale.com                      |        |              | 
(10 rows)

**Comment by arnaud-morvan** [comment]
L'essai s'est bien déroulé sur la démo.
J'ai changé le owner des posts,
j'ai supprimé les utilisateurs,
et le script sync_sso est en cours ...

**Comment by jmarcmod** [comment]
Je suis un peu largué par tout ça, et n'ai pas le temps d'aller vérifier ces comptes sur la démo.
@fbunoz tu peux jeter un œil ?

**Comment by arnaud-morvan** [comment]
Comme ca c'est bien déroulé sur la démo, je prévoie de faire la manip prochainement (cette semaine) sur la prod.
Eventuellement on pourrai également envoyer un mail au 3 utilisateurs concerné pour les prévenir que nous sommes intervenus sur leurs posts.

**Comment by jmarcmod** [comment]
Super !
Je peux me charger des mails, mais que faut-il leur dire exactement ?

**Comment by arnaud-morvan** [comment]
Les utilisateurs concernés sont : 

pvantiel / pvantiel1  - pvtiel@gmail.com
alex_buisse / alex_buisse_2 - public@alexbuisse.com
rabbits / rabbits1 - florian.daubarede@outlook.fr
tsan / tsan1 - thibaut.com@yahoo.com

Ces utilisateurs ayant à priori changé leur adresse email entre les deux migrations (forum / topoguide), lorsqu'ils se sont loggués, le système SSO leur a créé un nouveau compte dans le forum.

Pour résoudre ce problème de doublons, nous avons basculé les posts faits par ces nouveaux utilisateurs (dans la v6.0) sur les anciens utilisateurs et nous avons supprimé les nouveaux utilisateurs (doublons).

Par contre, s'ils ont fait des customisations depuis la mise en place de la V6.0 (ex: avatar, etc), ces réglages ont donc été perdus.

Je vais lancer dans la foulée la synchronisation finale de tous les utilisateurs en SSO (nous aurons ainsi dans discourse un enregistrement SSO pour tous les utilisateurs avec le user_id du topoguide et donc plus de risque de créer des doubons.
**Nous pourrons donc leur envoyer un mail demain.**

**Comment by jmarcmod** [comment]
>Nous pourrons donc leur envoyer un mail demain.

OK je m'en chargerai.

**Comment by arnaud-morvan** [comment]
A noter, concernant "tsan", j'ai réussi tant bien que mal a basculer ses messages privés (en brute sur la base, pas possible par l'interface).
```
UPDATE topics SET user_id = 27648 WHERE user_id = 50137;
UPDATE posts SET user_id = 27648 WHERE user_id = 50137;
UPDATE posts SET reply_to_user_id = 27648 WHERE reply_to_user_id = 50137;
UPDATE topic_allowed_users SET user_id = 27648 WHERE user_id = 50137;
```

**Comment by jmarcmod** [comment]
4 mails envoyés.

**Comment by arnaud-morvan** [comment]
Le traitement sync_sso s'est bien terminé, à part un forbidden sur marjenn et fifadelia.
Le problème initial semble bien réglé : 
https://forum.camptocamp.org/admin/users/10095/sam_le_pirate
https://forum.camptocamp.org/users/sam_le_pirate/activity
https://forum.camptocamp.org/admin/users/31070/samlepirate
https://forum.camptocamp.org/users/samlepirate/activity

**Comment by arnaud-morvan** [comment]
Tout les problème semblent réglés, je pense que nous pouvons fermer le ticket.

**Comment by jmarcmod** [comment]
Good job !
Plusieurs membres nous remercient pour la récupération d'un compte désormais fonctionnel.
