### ISSUE TITLE
Upgrade Discourse

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_forum#91]
A new stabilized version of Discourse has been released : 1.7.0.
We can update the c2c Discourse instance to this version.
Be careful, it exists already a version 1.8.0 beta.

The new features and bug fix are listed here : https://meta.discourse.org/t/discourse-version-1-7/41842

**Comment by asaunier** [comment]
In prod we currently use version 1.6.7
@mfournier has upgraded Discourse in the demo a few weeks/months ago to version 1.8.1

The upgraded forum on the demo seems to work except that user authenticating no longer works: a user authenticated in the guidebook is not authenticated in discourse and trying to log in from Discourse causes an "unknown error".
=> there is probably something broken about the authentication (perhaps a missing config in the admin?). @arnaud-morvan do you see what it could be?

https://meta.discourse.org/ currently runs Discourse 1.9.0beta10
The last stable version is 1.8.7 according to https://github.com/discourse/discourse

**Comment by asaunier** [comment]
As observed by @fbunoz it is possible to authenticate in the forum of the demo by making sure the authentication page, that the forum's login button redirects to, is in http, not https.

Then I have been able to authenticate successfully both form the UI or the forum and remain authenticated in Discourse.

On the other if I make sure to always use https pages (both in UI and Discourse), I still get the "unknown error" when trying to log in from Discourse.

**Comment by asaunier** [comment]
Perhaps that's because of some hard-coded http/https URL either in the demo Discourse admin or in the API config. In the demo API ``docker-compose.yml`` file I see:
```
    environment:
      ...
      discourse_url: 'http://forum.demov6.camptocamp.org'
      discourse_public_url: 'https://forum.demov6.camptocamp.org'
```

It seems we had the same problem before upgrading Discourse => than it might be OK with the prod?

**Comment by arnaud-morvan** [comment]
I've just logged in on demov6 forum, everythings go fine except that the certificate is not accepted by the browser.
Authentication on discourse is done by an iframe in guidebook after login, so if the request fails because of an unaccepted certificate, you do not get cookie in forum space.
Try to accept forum certificate before logging in.

@mfournier : is it possible to get a correct certificate on demo to avoid losing more time with this type of issues.

**Comment by mfournier** [comment]
upgraded to latest stable (1.8.8) just now.
