### ISSUE TITLE
Error 503 on server

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_forum#92]
There are often some 503 error on the forum. The service come back after 20-60s.

I was be able to generate 503 error on demand, by searching all topics without responses. But after 5-6 errors, the search returns results without 503 errors.

The request : /search?q=posts_count%3A1+order%3Alatest&_=1484142023932
Add https://forum.camptocamp.org add the begining of the url (I don't want to publish this url).

**Comment by mfournier** [comment]
This was due to the still unresolved issue with our redis setup. I had to reboot the machine more or less at the time you were experiencing this problem.

So closing this issue, at it's transient and unrelated to discourse itself.
