### ISSUE TITLE
Access-Control-Allow-Origin on API

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/v6_forum#93]
Bonjour,

Je crois que vous n'avez pas déclaré de Access-Control-Allow-Origin sur le serveur, du coup, l'API n'est pas utilisable en mode partagé. Si ce n'est pas volontaire, ça serait possible de l'ouvrir?

Pour tester, faites simplement l'url suivante : https://forum.camptocamp.org/top.json
Ca marche dans le navigateur, mais pas si vous requetez depuis un site via ajax.

**Comment by asaunier** [comment]
Duplicate of https://github.com/c2corg/v6_forum/issues/98
