### ISSUE TITLE
Frequent unexpected logouts in Discourse

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_forum#99]
It seems people are frequently logged out from Discourse whereas they are still authenticated in the guidebook part of the website.

Perhaps a hint: I have the feeling it's not that frequent when always using the same device rather than when being authenticated on several devices (eg. several computers) at the same time?

**Comment by asaunier** [comment]
I'm pretty sure the unexpected logouts are related to the use of several devices to visit the forum. I think I remain authenticated when using the same computer for a few days (eg. during WE). But for instance if I log in on my laptop at home, I am really often logged out when using my PC at the office, and vice versa.

Edit: that's for sure: it is not possible to be authenticated in Discourse on several devices at the same time.

**Comment by arnaud-morvan** [comment]
I see that there is a parameter in discouse admin:
```
log out strict
 When logging out, log out ALL sessions for the user on all devices
```
which is checked.

We should give it a chance.

**Comment by asaunier** [comment]
@fbunoz What do you think?

**Comment by arnaud-morvan** [comment]
We should try to reproduce with this parameter unchecked.

**Comment by fbunoz** [comment]
Arnaud has right.
I unchecked this parameter.

But before changing it, I could be authenticated in Discourse on several devices at the same time, by logging in one by one.
It was just when I logged out : I was logged out on all the devices.

**Comment by asaunier** [comment]
The new setting seems to have fixed the problem => closing the issue.
Perhaps we have another problem though if the session is not closed on all devices when logging out from one device (I think the API session is closed on all devices). But that's another issue.
